# Self-contained VM build for FileKeep.
# Embeds the fixed installer source (base64) so only ONE file
# needs to be transferred - no URLs to go stale.
#
# On the VM, run:
#   iwr "<this-script-url>" -OutFile C:\ub\run.ps1
#   C:\ub\run.ps1

$ErrorActionPreference = "Stop"

# Code signing configuration (all optional - build works without signing).
# Set these as environment variables on the build VM:
#   UB_SIGN_THUMBPRINT - Certificate thumbprint in LocalMachine\My store
#   UB_SIGN_PFX        - Path to .pfx/.p12 certificate file
#   UB_SIGN_PFX_PASSWORD - Password for the PFX file (consider using a secure vault)
#   UB_SKIP_SIGNING    - Set to "1" to explicitly skip signing
#
# The signing step uses signtool.exe from the Windows SDK. Timestamping is
# always applied so signatures remain valid after the cert expires.

function Invoke-CodeSigning {
    param([string[]]$Files)

    if ($env:UB_SKIP_SIGNING -eq "1") {
        Write-Host "  Signing skipped (UB_SKIP_SIGNING=1)."
        return
    }

    $signtool = $null
    foreach ($p in @(
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.26100.0\x64\signtool.exe",
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin\x64\signtool.exe"
    )) {
        if (Test-Path $p) { $signtool = $p; break }
    }
    if (-not $signtool) {
        $signtool = (Get-Command signtool.exe -ErrorAction SilentlyContinue).Source
    }
    if (-not $signtool) {
        Write-Host "  WARNING: signtool.exe not found - skipping code signing."
        Write-Host "  Install the Windows SDK to enable signing."
        return
    }

    $timestampUrl = "http://timestamp.digicert.com"
    $signed = 0

    foreach ($f in $Files) {
        if (-not (Test-Path $f)) {
            Write-Host "  WARNING: file not found, skipping: $f"
            continue
        }

        $args = @("sign", "/tr", $timestampUrl, "/td", "sha256", "/fd", "sha256")

        if ($env:UB_SIGN_THUMBPRINT) {
            $args += @("/sha1", $env:UB_SIGN_THUMBPRINT)
            Write-Host "  Signing $f with cert thumbprint $($env:UB_SIGN_THUMBPRINT.Substring(0,8))..."
        } elseif ($env:UB_SIGN_PFX) {
            $args += @("/f", $env:UB_SIGN_PFX)
            if ($env:UB_SIGN_PFX_PASSWORD) {
                $args += @("/p", $env:UB_SIGN_PFX_PASSWORD)
            }
            Write-Host "  Signing $f with PFX $env:UB_SIGN_PFX..."
        } else {
            Write-Host "  No signing certificate configured (set UB_SIGN_THUMBPRINT or UB_SIGN_PFX)."
            Write-Host "  Skipping code signing - build will be unsigned."
            return
        }

        $args += $f
        & $signtool @args
        if ($LASTEXITCODE -ne 0) { throw "signtool failed for $f" }

        # Verify the signature
        & $signtool verify /pa $f | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "Signature verification failed for $f" }

        Write-Host "  Signed and verified: $f"
        $signed++
    }

    Write-Host "  Signed $signed file(s)."
}

# Log everything to C:\ub\build.log: RDP drops do not kill the script on the
# VM, so if the session disconnects, reconnect and read the log for progress.
$transcript = "C:\ub\build.log"
try { Stop-Transcript | Out-Null } catch { }
Start-Transcript -Path $transcript -Append | Out-Null
Write-Host "Logging to $transcript"

try {

Write-Host "=== 1/6 Writing embedded installer source ==="
$wxsB64 = @"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCEtLSBXaVggdjUgaW5zdGFsbGVyIGZvciBGaWxlS2VlcC4KICAgICBUaGUgYXBwcyBwdWJsaXNoIGFzIHNpbmdsZS1maWxlIGV4ZWN1dGFibGVzIChQdWJsaXNoU2luZ2xlRmlsZSBpbiB0aGUKICAgICBjc3Byb2opLCBzbyB0aGUgcGF5bG9hZCBpcyBhIGhhbmRmdWwgb2YgZXhwbGljaXQgZmlsZXMg4oCUIG5vIGhhcnZlc3RpbmcuCiAgICAgQnVpbGQgb24gV2luZG93cyB3aXRoIHRoZSBXaVggdjUgZG90bmV0IHRvb2w6CiAgICAgICB3aXggYnVpbGQgLWFyY2ggeDY0IC1kIFNyY1Jvb3Q9QzpcdWJcc3JjIC1kIENsaUJpbj1DOlx1YlxwdWJsaXNoXGNsaSAtZCBTZXJ2aWNlQmluPUM6XHViXHB1Ymxpc2hcc2VydmljZSAtZCBSZWNvdmVyeUJpbj1DOlx1YlxwdWJsaXNoXHJlY292ZXJ5IC1vIHVzZW5ldC1iYWNrdXAtMC44LjEteDY0Lm1zaSBpbnN0YWxsL1VzZW5ldEJhY2t1cC53eHMKICAgICBJTVBPUlRBTlQ6IHJlLXB1Ymxpc2ggd2l0aCB0aGUgY3VycmVudCBjc3Byb2ogKHNpbmdsZS1maWxlKSBiZWZvcmUgYnVpbGRpbmc7CiAgICAgdGhlIE1TSSBpbnN0YWxscyBvbmx5IHRoZSBmaWxlcyBsaXN0ZWQgYmVsb3cuCi0tPgo8V2l4IHhtbG5zPSJodHRwOi8vd2l4dG9vbHNldC5vcmcvc2NoZW1hcy92NC93eHMiPgogIDxQYWNrYWdlIE5hbWU9IkZpbGVLZWVwIgogICAgICAgICAgIFZlcnNpb249IjAuOC4xIgogICAgICAgICAgIE1hbnVmYWN0dXJlcj0iSi4gVHJlaWNoZWwiCiAgICAgICAgICAgVXBncmFkZUNvZGU9IkY2RTBENkQxLTYxQTEtNDg0My04N0I5LTI4MjVBNDdBMThERCIKICAgICAgICAgICBTY29wZT0icGVyTWFjaGluZSI+CgogICAgPE1ham9yVXBncmFkZSBEb3duZ3JhZGVFcnJvck1lc3NhZ2U9IkEgbmV3ZXIgdmVyc2lvbiBvZiBGaWxlS2VlcCBpcyBhbHJlYWR5IGluc3RhbGxlZC4iIC8+CgogICAgPE1lZGlhIElkPSIxIiBDYWJpbmV0PSJwcm9kdWN0LmNhYiIgRW1iZWRDYWI9InllcyIgLz4KCiAgICA8U3RhbmRhcmREaXJlY3RvcnkgSWQ9IlByb2dyYW1GaWxlczY0MzJGb2xkZXIiPgogICAgICA8RGlyZWN0b3J5IElkPSJJTlNUQUxMRk9MREVSIiBOYW1lPSJGaWxlS2VlcCI+CiAgICAgICAgPERpcmVjdG9yeSBJZD0iQ0xJRElSIiBOYW1lPSJjbGkiIC8+CiAgICAgICAgPERpcmVjdG9yeSBJZD0iU0VSVklDRURJUiIgTmFtZT0ic2VydmljZSIgLz4KICAgICAgICA8RGlyZWN0b3J5IElkPSJXSVpBUkRESVIiIE5hbWU9IndpemFyZCIgLz4KICAgICAgICA8RGlyZWN0b3J5IElkPSJET0NTRElSIiBOYW1lPSJkb2NzIiAvPgogICAgICAgIDxEaXJlY3RvcnkgSWQ9IldJTlJFRElSIiBOYW1lPSJ3aW5yZSIgLz4KICAgICAgPC9EaXJlY3Rvcnk+CiAgICA8L1N0YW5kYXJkRGlyZWN0b3J5PgoKICAgIDwhLS0gQ0xJIChzaW5nbGUtZmlsZSBleGU7IG5hdGl2ZSBTUUxpdGUgaXMgYnVuZGxlZCBpbnNpZGUpIC0tPgogICAgPENvbXBvbmVudEdyb3VwIElkPSJDbGlGaWxlcyIgRGlyZWN0b3J5PSJDTElESVIiPgogICAgICA8Q29tcG9uZW50IElkPSJDbGlFeGUiIEd1aWQ9IioiPgogICAgICAgIDxGaWxlIElkPSJDbGlFeGVGaWxlIiBTb3VyY2U9IiQodmFyLkNsaUJpbilcRmlsZUtlZXAuZXhlIiBLZXlQYXRoPSJ5ZXMiIC8+CiAgICAgICAgPEZpbGUgSWQ9IlZzc0hlbHBlckV4ZSIgU291cmNlPSIkKHZhci5Wc3NCaW4pXEZpbGVLZWVwVnNzLmV4ZSIgLz4KICAgICAgICA8UmVtb3ZlRmlsZSBJZD0iUmVtb3ZlQ2xpUGRiIiBEaXJlY3Rvcnk9IkNMSURJUiIgTmFtZT0iKi5wZGIiIE9uPSJ1bmluc3RhbGwiIC8+CiAgICAgICAgPFJlbW92ZUZvbGRlciBJZD0iUmVtb3ZlQ2xpRGlyIiBEaXJlY3Rvcnk9IkNMSURJUiIgT249InVuaW5zdGFsbCIgLz4KICAgICAgPC9Db21wb25lbnQ+CiAgICA8L0NvbXBvbmVudEdyb3VwPgoKICAgIDxDb21wb25lbnRHcm91cCBJZD0iU2VydmljZVJlZ2lzdHJhdGlvbiIgRGlyZWN0b3J5PSJTRVJWSUNFRElSIj4KICAgICAgPENvbXBvbmVudCBJZD0iU2VydmljZUV4ZWN1dGFibGUiPgogICAgICAgIDxGaWxlIElkPSJTZXJ2aWNlRXhlIiBTb3VyY2U9IiQodmFyLlNlcnZpY2VCaW4pXEZpbGVLZWVwU2VydmljZS5leGUiIEtleVBhdGg9InllcyIgLz4KICAgICAgICA8U2VydmljZUluc3RhbGwgSWQ9IkJhY2t1cFNlcnZpY2UiCiAgICAgICAgICAgICAgICAgICAgICAgIFR5cGU9Im93blByb2Nlc3MiCiAgICAgICAgICAgICAgICAgICAgICAgIE5hbWU9IkZpbGVLZWVwIgogICAgICAgICAgICAgICAgICAgICAgICBEaXNwbGF5TmFtZT0iRmlsZUtlZXAgU2VydmljZSIKICAgICAgICAgICAgICAgICAgICAgICAgRGVzY3JpcHRpb249IlNjaGVkdWxlZCBlbmNyeXB0ZWQgYmFja3VwcyB0byBVc2VuZXQuIgogICAgICAgICAgICAgICAgICAgICAgICBTdGFydD0iYXV0byIKICAgICAgICAgICAgICAgICAgICAgICAgQWNjb3VudD0iTG9jYWxTeXN0ZW0iCiAgICAgICAgICAgICAgICAgICAgICAgIEVycm9yQ29udHJvbD0ibm9ybWFsIiAvPgogICAgICAgIDxTZXJ2aWNlQ29udHJvbCBJZD0iQmFja3VwU2VydmljZUNvbnRyb2wiCiAgICAgICAgICAgICAgICAgICAgICAgIE5hbWU9IkZpbGVLZWVwIgogICAgICAgICAgICAgICAgICAgICAgICBTdG9wPSJib3RoIgogICAgICAgICAgICAgICAgICAgICAgICBSZW1vdmU9InVuaW5zdGFsbCIKICAgICAgICAgICAgICAgICAgICAgICAgV2FpdD0idHJ1ZSIgLz4KICAgICAgICA8IS0tIENsZWFuIHVwIHJ1bnRpbWUtY3JlYXRlZCBmaWxlcyAoc2VydmljZSB3cml0ZXMgY29uZmlnL2xvZ3MgaGVyZSwgc2luZ2xlLWZpbGUgZXhlIGV4dHJhY3RzIG5hdGl2ZSBsaWJzKSAtLT4KICAgICAgICA8UmVtb3ZlRmlsZSBJZD0iUmVtb3ZlU2VydmljZUpzb24iIERpcmVjdG9yeT0iU0VSVklDRURJUiIgTmFtZT0ic2VydmljZS5qc29uIiBPbj0idW5pbnN0YWxsIiAvPgogICAgICAgIDxSZW1vdmVGaWxlIElkPSJSZW1vdmVTZXJ2aWNlTG9nIiBEaXJlY3Rvcnk9IlNFUlZJQ0VESVIiIE5hbWU9InNlcnZpY2UubG9nIiBPbj0idW5pbnN0YWxsIiAvPgogICAgICAgIDxSZW1vdmVGaWxlIElkPSJSZW1vdmVTcWxpdGVEbGwiIERpcmVjdG9yeT0iU0VSVklDRURJUiIgTmFtZT0iZV9zcWxpdGUzLmRsbCIgT249InVuaW5zdGFsbCIgLz4KICAgICAgICA8UmVtb3ZlRmlsZSBJZD0iUmVtb3ZlU2VydmljZVBkYiIgRGlyZWN0b3J5PSJTRVJWSUNFRElSIiBOYW1lPSIqLnBkYiIgT249InVuaW5zdGFsbCIgLz4KICAgICAgICA8UmVtb3ZlRmlsZSBJZD0iUmVtb3ZlQXNwTmV0RGxsIiBEaXJlY3Rvcnk9IlNFUlZJQ0VESVIiIE5hbWU9ImFzcG5ldGNvcmV2Ml9pbnByb2Nlc3MuZGxsIiBPbj0idW5pbnN0YWxsIiAvPgogICAgICAgIDxSZW1vdmVGaWxlIElkPSJSZW1vdmVXZWJDb25maWciIERpcmVjdG9yeT0iU0VSVklDRURJUiIgTmFtZT0id2ViLmNvbmZpZyIgT249InVuaW5zdGFsbCIgLz4KICAgICAgICA8UmVtb3ZlRm9sZGVyIElkPSJSZW1vdmVTZXJ2aWNlRGlyIiBEaXJlY3Rvcnk9IlNFUlZJQ0VESVIiIE9uPSJ1bmluc3RhbGwiIC8+CiAgICAgIDwvQ29tcG9uZW50PgogICAgPC9Db21wb25lbnRHcm91cD4KCiAgICA8IS0tIFJlY292ZXJ5IHdpemFyZCAoc2luZ2xlLWZpbGUgZXhlOyBuYXRpdmUgU1FMaXRlIGlzIGJ1bmRsZWQgaW5zaWRlKSAtLT4KICAgIDxDb21wb25lbnRHcm91cCBJZD0iUmVjb3ZlcnlGaWxlcyIgRGlyZWN0b3J5PSJXSVpBUkRESVIiPgogICAgICA8Q29tcG9uZW50IElkPSJSZWNvdmVyeUV4ZSIgR3VpZD0iKiI+CiAgICAgICAgPEZpbGUgSWQ9IlJlY292ZXJ5RXhlRmlsZSIgU291cmNlPSIkKHZhci5SZWNvdmVyeUJpbilcRmlsZUtlZXBSZWNvdmVyeS5leGUiIEtleVBhdGg9InllcyIgLz4KICAgICAgICA8UmVtb3ZlRm9sZGVyIElkPSJSZW1vdmVXaXphcmREaXIiIERpcmVjdG9yeT0iV0laQVJERElSIiBPbj0idW5pbnN0YWxsIiAvPgogICAgICA8L0NvbXBvbmVudD4KICAgIDwvQ29tcG9uZW50R3JvdXA+CgogICAgPCEtLSBTZXJ2aWNlIGNvbmZpZyBleGFtcGxlICsgcmVjb3ZlcnkgcnVuYm9vayAtLT4KICAgIDxDb21wb25lbnRHcm91cCBJZD0iRG9jcyIgRGlyZWN0b3J5PSJET0NTRElSIj4KICAgICAgPENvbXBvbmVudCBJZD0iRG9jc0NvbXBvbmVudCIgR3VpZD0iNDM2MzFGMDAtMjZDQi00NkE3LUJEOEYtMzhEQjQ0RUM0QTU0Ij4KICAgICAgICA8RmlsZSBTb3VyY2U9IiQodmFyLlNyY1Jvb3QpXHNyY1xVc2VuZXRCYWNrdXAuU2VydmljZVxzZXJ2aWNlLmV4YW1wbGUuanNvbiIgTmFtZT0ic2VydmljZS5leGFtcGxlLmpzb24iIC8+CiAgICAgICAgPEZpbGUgU291cmNlPSIkKHZhci5TcmNSb290KVxkb2NzXFJFQ09WRVJZLm1kIiBOYW1lPSJSRUNPVkVSWS5tZCIgLz4KICAgICAgICA8RmlsZSBTb3VyY2U9IiQodmFyLlNyY1Jvb3QpXExJQ0VOU0UiIE5hbWU9IkxJQ0VOU0UudHh0IiAvPgogICAgICAgIDxGaWxlIFNvdXJjZT0iJCh2YXIuU3JjUm9vdClcZG9jc1xUSElSRC1QQVJUWS1OT1RJQ0VTLm1kIiBOYW1lPSJUSElSRC1QQVJUWS1OT1RJQ0VTLm1kIiAvPgogICAgICAgIDxSZW1vdmVGb2xkZXIgSWQ9IlJlbW92ZURvY3NEaXIiIERpcmVjdG9yeT0iRE9DU0RJUiIgT249InVuaW5zdGFsbCIgLz4KICAgICAgICA8UmVtb3ZlRm9sZGVyIElkPSJSZW1vdmVJbnN0YWxsRGlyIiBEaXJlY3Rvcnk9IklOU1RBTExGT0xERVIiIE9uPSJ1bmluc3RhbGwiIC8+CiAgICAgIDwvQ29tcG9uZW50PgogICAgPC9Db21wb25lbnRHcm91cD4KCgogICAgPCEtLSBXaW5SRSBVU0IgYnVpbGQgc2NyaXB0ICh1c2VkIGJ5IHRoZSBkYXNoYm9hcmQncyBXaW5SRSBVU0IgR1VJOyBBREstZnJlZSkgLS0+CiAgICA8Q29tcG9uZW50R3JvdXAgSWQ9IldpblJFRmlsZXMiIERpcmVjdG9yeT0iV0lOUkVESVIiPgogICAgICA8Q29tcG9uZW50IElkPSJXaW5SRUJ1aWxkU2NyaXB0IiBHdWlkPSIqIj4KICAgICAgICA8RmlsZSBTb3VyY2U9IiQodmFyLlNyY1Jvb3QpXHdpbnJlXGJ1aWxkLXdpbnJlLXVzYi5wczEiIE5hbWU9ImJ1aWxkLXdpbnJlLXVzYi5wczEiIEtleVBhdGg9InllcyIgLz4KICAgICAgICA8UmVtb3ZlRm9sZGVyIElkPSJSZW1vdmVXaW5SRURpciIgRGlyZWN0b3J5PSJXSU5SRURJUiIgT249InVuaW5zdGFsbCIgLz4KICAgICAgPC9Db21wb25lbnQ+CiAgICA8L0NvbXBvbmVudEdyb3VwPgoKICAgIDxGZWF0dXJlIElkPSJQcm9kdWN0RmVhdHVyZSIgVGl0bGU9IkZpbGVLZWVwIiBMZXZlbD0iMSI+CiAgICAgIDxDb21wb25lbnRHcm91cFJlZiBJZD0iQ2xpRmlsZXMiIC8+CiAgICAgIDxDb21wb25lbnRHcm91cFJlZiBJZD0iU2VydmljZVJlZ2lzdHJhdGlvbiIgLz4KICAgICAgPENvbXBvbmVudEdyb3VwUmVmIElkPSJSZWNvdmVyeUZpbGVzIiAvPgogICAgICA8Q29tcG9uZW50R3JvdXBSZWYgSWQ9IkRvY3MiIC8+CiAgICAgIDxDb21wb25lbnRHcm91cFJlZiBJZD0iV2luUkVGaWxlcyIgLz4KICAgIDwvRmVhdHVyZT4KCiAgICA8IS0tIEFkZC9SZW1vdmUgUHJvZ3JhbXMgaWNvbiAtLT4KICAgIDxJY29uIElkPSJGaWxlS2VlcEljb24iIFNvdXJjZUZpbGU9IiQodmFyLlNyY1Jvb3QpL2Fzc2V0cy9maWxla2VlcC5pY28iIC8+CiAgICA8UHJvcGVydHkgSWQ9IkFSUFBST0RVQ1RJQ09OIiBWYWx1ZT0iRmlsZUtlZXBJY29uIiAvPgoKICAgIDwhLS0gSW5zdGFsbGVyIGJhbm5lciAodG9wKSBhbmQgZGlhbG9nIChzaWRlKSBiaXRtYXBzIC0tPgogICAgPFdpeFZhcmlhYmxlIElkPSJXaXhVSUJhbm5lckJtcCIgVmFsdWU9IiQodmFyLlNyY1Jvb3QpL2Fzc2V0cy9maWxla2VlcC1iYW5uZXIuYm1wIiAvPgogICAgPFdpeFZhcmlhYmxlIElkPSJXaXhVSURpYWxvZ0JtcCIgVmFsdWU9IiQodmFyLlNyY1Jvb3QpL2Fzc2V0cy9maWxla2VlcC1kaWFsb2cuYm1wIiAvPgogIDwvUGFja2FnZT4KPC9XaXg+Cg=="@
$winreB64 = @"
IyBCdWlsZHMgYSBib290YWJsZSBGaWxlS2VlcCByZWNvdmVyeSBVU0IgZnJvbSB0aGUgaG9zdCdzIFdpblJFIGltYWdlLgojIEFESy1mcmVlOiB1c2VzIG9ubHkgaW4tYm94IFdpbmRvd3MgY29tcG9uZW50cyAocmVhZ2VudGMsIERJU00sIGJjZGJvb3QpLgojCiMgUnVuIG9uIFdpbmRvd3MgYXMgQWRtaW5pc3RyYXRvci4KIwojIEZsb3c6CiMgICAxLiBMb2NhdGUgV2luUkUgdmlhIHJlYWdlbnRjIC9pbmZvCiMgICAyLiBUZW1wb3JhcmlseSBkaXNhYmxlIFdpblJFIChyZWxlYXNlcyB0aGUgV0lNIGxvY2spCiMgICAzLiBNb3VudCB3aW5yZS53aW0gd2l0aCBESVNNCiMgICA0LiBJbmplY3QgRmlsZUtlZXAgcmVjb3ZlcnkgdG9vbHMgaW50byB0aGUgbW91bnRlZCBpbWFnZQojICAgNS4gQ29tbWl0IGFuZCB1bm1vdW50CiMgICA2LiBQcmVwYXJlIHRoZSBVU0IgZHJpdmUgKEZBVDMyLCBib290IGZpbGVzIHZpYSBiY2Rib290KQojICAgNy4gQ29weSB0aGUgY3VzdG9taXplZCB3aW5yZS53aW0gdG8gdGhlIFVTQgojICAgOC4gUmUtZW5hYmxlIFdpblJFIG9uIHRoZSBob3N0CiMKIyBUd28gbW9kZXM6CiMgICAxLiBTb3VyY2UgbW9kZSAoZGV2KTogcHVibGlzaGVzIGZyb20gYSBzb3VyY2UgdHJlZS4KIyAgICAgIC5cd2lucmVcYnVpbGQtd2lucmUtdXNiLnBzMSAtRHJpdmVMZXR0ZXIgRSAtU291cmNlRGlyIEM6XHViXHNyYwojICAgMi4gQmluYXJ5IG1vZGUgKGluc3RhbGxlZCk6IHVzZXMgcHJlLXB1Ymxpc2hlZCBiaW5hcmllcywgZS5nLiBmcm9tCiMgICAgICBDOlxQcm9ncmFtIEZpbGVzXEZpbGVLZWVwLiBUaGUgZGFzaGJvYXJkJ3MgV2luUkUgR1VJIHVzZXMgdGhpcyBtb2RlLgojICAgICAgLlx3aW5yZVxidWlsZC13aW5yZS11c2IucHMxIC1Ecml2ZUxldHRlciBFIC1CaW5hcnlEaXIgIkM6XFByb2dyYW0gRmlsZXNcRmlsZUtlZXAiCiMKIyBJbiBiaW5hcnkgbW9kZSB0aGUgbGF5b3V0IGlzIGV4cGVjdGVkIHRvIGJlOgojICAgPEJpbmFyeURpcj5cY2xpXEZpbGVLZWVwLmV4ZQojICAgPEJpbmFyeURpcj5cd2l6YXJkXEZpbGVLZWVwUmVjb3ZlcnkuZXhlCiMgICA8QmluYXJ5RGlyPlxkb2NzXFJFQ09WRVJZLm1kCiMKIyBXQVJOSU5HOiBEZXN0cnVjdGl2ZSDigJQgdGhlIHRhcmdldCBVU0IgZHJpdmUgaXMgZm9ybWF0dGVkLgoKcGFyYW0oCiAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0kdHJ1ZSldCiAgICBbc3RyaW5nXSREcml2ZUxldHRlciwKICAgIFtzdHJpbmddJFNvdXJjZURpciA9ICJDOlx1YlxzcmMiLAogICAgW3N0cmluZ10kQmluYXJ5RGlyID0gIiIsCiAgICBbc3RyaW5nXSRNb3VudERpciA9ICJDOlx3aW5yZS1tb3VudCIsCiAgICBbc3dpdGNoXSRTa2lwUmVlbmFibGUKKQoKJEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJTdG9wIgoKZnVuY3Rpb24gRmFpbCgkbXNnKSB7IFdyaXRlLUVycm9yICRtc2c7IGV4aXQgMSB9CgojIC0tLSBQcmVjb25kaXRpb25zIC0tLQppZiAoLW5vdCAoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsXVtTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0lkZW50aXR5XTo6R2V0Q3VycmVudCgpKS5Jc0luUm9sZShbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NCdWlsdEluUm9sZV06OkFkbWluaXN0cmF0b3IpKSB7CiAgICBGYWlsICJSdW4gYXMgQWRtaW5pc3RyYXRvci4iCn0KaWYgKC1ub3QgKEdldC1Db21tYW5kIHJlYWdlbnRjLmV4ZSAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSkpIHsgRmFpbCAicmVhZ2VudGMuZXhlIG5vdCBmb3VuZC4iIH0KaWYgKC1ub3QgKEdldC1Db21tYW5kIGRpc20uZXhlIC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSkgeyBGYWlsICJkaXNtLmV4ZSBub3QgZm91bmQuIiB9CmlmICgtbm90IChHZXQtQ29tbWFuZCBiY2Rib290LmV4ZSAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSkpIHsgRmFpbCAiYmNkYm9vdC5leGUgbm90IGZvdW5kLiIgfQoKIyBOb3JtYWxpemUgZHJpdmUgbGV0dGVyIChhY2NlcHQgIkUiLCAiRToiLCAiRTpcIikKJERyaXZlTGV0dGVyID0gJERyaXZlTGV0dGVyLlRyaW1FbmQoJzonLCAnXCcpCmlmICgkRHJpdmVMZXR0ZXIuTGVuZ3RoIC1uZSAxKSB7IEZhaWwgIkRyaXZlTGV0dGVyIG11c3QgYmUgYSBzaW5nbGUgbGV0dGVyIChlLmcuIEUpLiIgfQokdXNiUm9vdCA9ICIkRHJpdmVMZXR0ZXJgOlwiCmlmICgtbm90IChUZXN0LVBhdGggJHVzYlJvb3QpKSB7IEZhaWwgIkRyaXZlICR1c2JSb290IG5vdCBmb3VuZC4iIH0KCiMgUmVmdXNlIHRvIHJ1biBhZ2FpbnN0IHRoZSBzeXN0ZW0gZHJpdmUgb3IgYSBmaXhlZCBpbnRlcm5hbCBkcml2ZS4KJHZvbCA9IEdldC1Wb2x1bWUgLURyaXZlTGV0dGVyICREcml2ZUxldHRlciAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQppZiAoJHZvbCAtYW5kICR2b2wuRHJpdmVUeXBlIC1uZSAnUmVtb3ZhYmxlJykgewogICAgV3JpdGUtV2FybmluZyAiRHJpdmUgJERyaXZlTGV0dGVyIGlzIG5vdCBtYXJrZWQgUmVtb3ZhYmxlICh0eXBlOiAkKCR2b2wuRHJpdmVUeXBlKSkuIgogICAgJGNvbmZpcm0gPSBSZWFkLUhvc3QgIlR5cGUgWUVTIHRvIGNvbnRpbnVlIGFueXdheSIKICAgIGlmICgkY29uZmlybSAtbmUgIllFUyIpIHsgRmFpbCAiQWJvcnRlZC4iIH0KfQoKV3JpdGUtSG9zdCAiPT09IEZpbGVLZWVwIFdpblJFIFVTQiBidWlsZGVyID09PSIKV3JpdGUtSG9zdCAiVGFyZ2V0IFVTQjogJHVzYlJvb3QiCgojIC0tLSBMb2NhdGUgV2luUkUgLS0tCldyaXRlLUhvc3QgIkxvY2F0aW5nIFdpblJFLi4uIgokcmVJbmZvID0gcmVhZ2VudGMgL2luZm8gMj4mMSB8IE91dC1TdHJpbmcKJHdpbVBhdGggPSAkbnVsbApmb3JlYWNoICgkbGluZSBpbiAkcmVJbmZvIC1zcGxpdCAiYHI/YG4iKSB7CiAgICBpZiAoJGxpbmUgLW1hdGNoICdXaW5kb3dzIFJFIGxvY2F0aW9uOlxzKiguKyknKSB7CiAgICAgICAgJGxvYyA9ICRNYXRjaGVzWzFdLlRyaW0oKQogICAgICAgICMgTG9jYXRpb24gaXMgbGlrZSBcXD9cR0xPQkFMUk9PVFxkZXZpY2VcaGFyZGRpc2swXHBhcnRpdGlvbjRcUmVjb3ZlcnlcV2luZG93c1JFCiAgICAgICAgIyBUaGUgV0lNIGl0c2VsZiBpcyB3aW5yZS53aW0gaW4gdGhhdCBkaXJlY3RvcnkuCiAgICAgICAgaWYgKCRsb2MgLW1hdGNoICdeW0EtWmEtel06XFwnKSB7CiAgICAgICAgICAgICR3aW1QYXRoID0gSm9pbi1QYXRoICRsb2MgIndpbnJlLndpbSIKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBXcml0ZS1Ib3N0ICJXaW5SRSBsb2NhdGlvbiBpcyBub3QgYSBwbGFpbiBwYXRoOiAkbG9jIgogICAgICAgICAgICBXcml0ZS1Ib3N0ICJBdHRlbXB0aW5nIHRvIHJlc29sdmUgdmlhIG1vdW50dm9sL0dMT0JBTFJPT1QuLi4iCiAgICAgICAgfQogICAgICAgIGJyZWFrCiAgICB9Cn0KIyBGYWxsYmFjazogcHJvYmUgdGhlIHN0YW5kYXJkIFJlY292ZXJ5IHBhdGggb24gdGhlIHN5c3RlbSBkcml2ZS4KaWYgKC1ub3QgJHdpbVBhdGggLW9yIC1ub3QgKFRlc3QtUGF0aCAkd2ltUGF0aCkpIHsKICAgICRzeXNEcml2ZSA9ICRlbnY6U3lzdGVtRHJpdmUKICAgIGZvcmVhY2ggKCRjYW5kaWRhdGUgaW4gQCgKICAgICAgICAiJHN5c0RyaXZlXFJlY292ZXJ5XFdpbmRvd3NSRVx3aW5yZS53aW0iLAogICAgICAgICIkc3lzRHJpdmVcV2luZG93c1xTeXN0ZW0zMlxSZWNvdmVyeVx3aW5yZS53aW0iCiAgICApKSB7CiAgICAgICAgaWYgKFRlc3QtUGF0aCAkY2FuZGlkYXRlKSB7ICR3aW1QYXRoID0gJGNhbmRpZGF0ZTsgYnJlYWsgfQogICAgfQp9CmlmICgtbm90ICR3aW1QYXRoIC1vciAtbm90IChUZXN0LVBhdGggJHdpbVBhdGgpKSB7CiAgICBGYWlsICJDb3VsZCBub3QgbG9jYXRlIHdpbnJlLndpbS4gRW5zdXJlIFdpblJFIGlzIGVuYWJsZWQgKHJlYWdlbnRjIC9pbmZvKS4iCn0KV3JpdGUtSG9zdCAiV2luUkUgaW1hZ2U6ICR3aW1QYXRoIgoKIyAtLS0gU3RhZ2UgRmlsZUtlZXAgYmluYXJpZXMgLS0tCiRzdGFnZURpciA9IEpvaW4tUGF0aCAoW0lPLlBhdGhdOjpHZXRUZW1wUGF0aCgpKSAiZmlsZWtlZXAtd2lucmUtc3RhZ2UiCiRjbGlPdXQgPSBKb2luLVBhdGggJHN0YWdlRGlyICJjbGkiCiR3aXpPdXQgPSBKb2luLVBhdGggJHN0YWdlRGlyICJyZWNvdmVyeSIKJGRvY3NPdXQgPSBKb2luLVBhdGggJHN0YWdlRGlyICJkb2NzIgpmb3JlYWNoICgkZCBpbiBAKCRjbGlPdXQsICR3aXpPdXQsICRkb2NzT3V0KSkgeyBOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSAtUGF0aCAkZCB8IE91dC1OdWxsIH0KCmlmICgkQmluYXJ5RGlyIC1uZSAiIikgewogICAgV3JpdGUtSG9zdCAiQmluYXJ5IG1vZGU6IGNvcHlpbmcgcHJlLXB1Ymxpc2hlZCBiaW5hcmllcyBmcm9tICRCaW5hcnlEaXIuLi4iCiAgICAkc3JjQ2xpID0gSm9pbi1QYXRoICRCaW5hcnlEaXIgImNsaVxGaWxlS2VlcC5leGUiCiAgICAkc3JjV2l6ID0gSm9pbi1QYXRoICRCaW5hcnlEaXIgIndpemFyZFxGaWxlS2VlcFJlY292ZXJ5LmV4ZSIKICAgIGlmICgtbm90IChUZXN0LVBhdGggJHNyY0NsaSkpIHsgRmFpbCAiQ0xJIG5vdCBmb3VuZDogJHNyY0NsaSIgfQogICAgaWYgKC1ub3QgKFRlc3QtUGF0aCAkc3JjV2l6KSkgeyBGYWlsICJXaXphcmQgbm90IGZvdW5kOiAkc3JjV2l6IiB9CiAgICBDb3B5LUl0ZW0gKEpvaW4tUGF0aCAkQmluYXJ5RGlyICJjbGlcKiIpICRjbGlPdXQgLVJlY3Vyc2UgLUZvcmNlCiAgICBDb3B5LUl0ZW0gKEpvaW4tUGF0aCAkQmluYXJ5RGlyICJ3aXphcmRcKiIpICR3aXpPdXQgLVJlY3Vyc2UgLUZvcmNlCiAgICAkc3JjRG9jcyA9IEpvaW4tUGF0aCAkQmluYXJ5RGlyICJkb2NzIgogICAgaWYgKFRlc3QtUGF0aCAkc3JjRG9jcykgeyBDb3B5LUl0ZW0gKEpvaW4tUGF0aCAkc3JjRG9jcyAiKiIpICRkb2NzT3V0IC1SZWN1cnNlIC1Gb3JjZSB9Cn0gZWxzZSB7CiAgICBXcml0ZS1Ib3N0ICJTb3VyY2UgbW9kZTogcHVibGlzaGluZyBmcm9tICRTb3VyY2VEaXIuLi4iCiAgICBpZiAoLW5vdCAoVGVzdC1QYXRoIChKb2luLVBhdGggJFNvdXJjZURpciAiRmlsZUtlZXAuc2xueCIpKSkgeyBGYWlsICJTb3VyY2UgdHJlZSBub3QgZm91bmQ6ICRTb3VyY2VEaXIiIH0KICAgIGlmICgtbm90IChHZXQtQ29tbWFuZCBkb3RuZXQgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUpKSB7IEZhaWwgImRvdG5ldCBTREsgbm90IGZvdW5kIChzb3VyY2UgbW9kZSByZXF1aXJlcyBpdCkuIiB9CiAgICBQdXNoLUxvY2F0aW9uICRTb3VyY2VEaXIKICAgIHRyeSB7CiAgICAgICAgZG90bmV0IHB1Ymxpc2ggc3JjL1VzZW5ldEJhY2t1cC5DbGkvVXNlbmV0QmFja3VwLkNsaS5jc3Byb2ogLWMgUmVsZWFzZSAtciB3aW4teDY0IC0tc2VsZi1jb250YWluZWQgLW8gJGNsaU91dAogICAgICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgImRvdG5ldCBwdWJsaXNoIChDTEkpIGZhaWxlZC4iIH0KICAgICAgICBkb3RuZXQgcHVibGlzaCBzcmMvVXNlbmV0QmFja3VwLlJlY292ZXJ5L1VzZW5ldEJhY2t1cC5SZWNvdmVyeS5jc3Byb2ogLWMgUmVsZWFzZSAtciB3aW4teDY0IC0tc2VsZi1jb250YWluZWQgLW8gJHdpek91dAogICAgICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgImRvdG5ldCBwdWJsaXNoIChSZWNvdmVyeSkgZmFpbGVkLiIgfQogICAgfSBmaW5hbGx5IHsgUG9wLUxvY2F0aW9uIH0KICAgICRzcmNEb2NzID0gSm9pbi1QYXRoICRTb3VyY2VEaXIgImRvY3NcUkVDT1ZFUlkubWQiCiAgICBpZiAoVGVzdC1QYXRoICRzcmNEb2NzKSB7IENvcHktSXRlbSAkc3JjRG9jcyAkZG9jc091dCAtRm9yY2UgfQp9CldyaXRlLUhvc3QgIlN0YWdlZCBGaWxlS2VlcCBiaW5hcmllcy4iCgojIC0tLSBEaXNhYmxlIFdpblJFIChyZWxlYXNlcyB0aGUgV0lNIGxvY2spIC0tLQokd2FzRW5hYmxlZCA9ICRyZUluZm8gLW1hdGNoICdFbmFibGVkJwppZiAoJHdhc0VuYWJsZWQpIHsKICAgIFdyaXRlLUhvc3QgIkRpc2FibGluZyBXaW5SRSB0ZW1wb3JhcmlseS4uLiIKICAgIHJlYWdlbnRjIC9kaXNhYmxlIHwgT3V0LU51bGwKICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgInJlYWdlbnRjIC9kaXNhYmxlIGZhaWxlZC4iIH0KfSBlbHNlIHsKICAgIFdyaXRlLUhvc3QgIldpblJFIGFscmVhZHkgZGlzYWJsZWQ7IHByb2NlZWRpbmcuIgp9Cgokd2lucmVSZWVuYWJsZWQgPSAkZmFsc2UKdHJ5IHsKICAgICMgLS0tIE1vdW50IHRoZSBXSU0gLS0tCiAgICBXcml0ZS1Ib3N0ICJNb3VudGluZyB3aW5yZS53aW0uLi4iCiAgICBpZiAoVGVzdC1QYXRoICRNb3VudERpcikgeyBSZW1vdmUtSXRlbSAkTW91bnREaXIgLVJlY3Vyc2UgLUZvcmNlIH0KICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICRNb3VudERpciB8IE91dC1OdWxsCiAgICAjIENvcHkgdGhlIFdJTSB0byBhIHRlbXAgbG9jYXRpb24gc28gdGhlIG9yaWdpbmFsIHN0YXlzIHByaXN0aW5lLgogICAgJHdpbUNvcHkgPSBKb2luLVBhdGggKFtJTy5QYXRoXTo6R2V0VGVtcFBhdGgoKSkgImZpbGVrZWVwLXdpbnJlLndpbSIKICAgIENvcHktSXRlbSAkd2ltUGF0aCAkd2ltQ29weSAtRm9yY2UKICAgIGRpc20gL01vdW50LVdpbSAvV2ltRmlsZTokd2ltQ29weSAvSW5kZXg6MSAvTW91bnREaXI6JE1vdW50RGlyCiAgICBpZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJESVNNIG1vdW50IGZhaWxlZC4iIH0KCiAgICB0cnkgewogICAgICAgICMgLS0tIEluamVjdCBGaWxlS2VlcCB0b29scyAtLS0KICAgICAgICBXcml0ZS1Ib3N0ICJJbmplY3RpbmcgRmlsZUtlZXAgcmVjb3ZlcnkgdG9vbHMuLi4iCiAgICAgICAgJGZrRGlyID0gSm9pbi1QYXRoICRNb3VudERpciAiRmlsZUtlZXAiCiAgICAgICAgTmV3LUl0ZW0gLUl0ZW1UeXBlIERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJGZrRGlyIHwgT3V0LU51bGwKICAgICAgICBDb3B5LUl0ZW0gKEpvaW4tUGF0aCAkc3RhZ2VEaXIgIioiKSAkZmtEaXIgLVJlY3Vyc2UgLUZvcmNlCgogICAgICAgICMgQWRkIGEgc3RhcnR1cCBob29rIHNvIHRoZSByZWNvdmVyeSB3aXphcmQgbGF1bmNoZXMgaW4gV2luUkUuCiAgICAgICAgIyBXaW5SRSBob25vcnMgV2lucGVzaGwuaW5pIGZvciBhIGN1c3RvbSBzaGVsbC4KICAgICAgICAkd2lucGVzaGwgPSBKb2luLVBhdGggJE1vdW50RGlyICJXaW5kb3dzXFN5c3RlbTMyXHdpbnBlc2hsLmluaSIKICAgICAgICAkd2lucGVzaGxDb250ZW50ID0gQCIKW0xhdW5jaEFwcHNdClg6XEZpbGVLZWVwXHJlY292ZXJ5XEZpbGVLZWVwUmVjb3ZlcnkuZXhlCiJACiAgICAgICAgIyBPbmx5IHdyaXRlIGlmIG5vdCBhbHJlYWR5IHByZXNlbnQgdG8gYXZvaWQgY2xvYmJlcmluZy4KICAgICAgICBpZiAoLW5vdCAoVGVzdC1QYXRoICR3aW5wZXNobCkpIHsKICAgICAgICAgICAgJHdpbnBlc2hsQ29udGVudCB8IE91dC1GaWxlICR3aW5wZXNobCAtRW5jb2RpbmcgYXNjaWkKICAgICAgICAgICAgV3JpdGUtSG9zdCAiQWRkZWQgd2lucGVzaGwuaW5pIHRvIGxhdW5jaCB0aGUgcmVjb3Zlcnkgd2l6YXJkLiIKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBXcml0ZS1Ib3N0ICJ3aW5wZXNobC5pbmkgYWxyZWFkeSBleGlzdHM7IGxlYXZpbmcgaXQgYWxvbmUuIgogICAgICAgIH0KICAgIH0gZmluYWxseSB7CiAgICAgICAgIyAtLS0gQ29tbWl0IGFuZCB1bm1vdW50IC0tLQogICAgICAgIFdyaXRlLUhvc3QgIkNvbW1pdHRpbmcgYW5kIHVubW91bnRpbmcuLi4iCiAgICAgICAgZGlzbSAvVW5tb3VudC1XaW0gL01vdW50RGlyOiRNb3VudERpciAvQ29tbWl0CiAgICAgICAgaWYgKCRMQVNURVhJVENPREUgLW5lIDApIHsKICAgICAgICAgICAgV3JpdGUtV2FybmluZyAiRElTTSBjb21taXQtdW5tb3VudCByZXBvcnRlZCBhbiBlcnJvcjsgYXR0ZW1wdGluZyBkaXNjYXJkLiIKICAgICAgICAgICAgZGlzbSAvVW5tb3VudC1XaW0gL01vdW50RGlyOiRNb3VudERpciAvRGlzY2FyZCB8IE91dC1OdWxsCiAgICAgICAgICAgIEZhaWwgIkRJU00gdW5tb3VudCAvY29tbWl0IGZhaWxlZC4iCiAgICAgICAgfQogICAgfQoKICAgICMgLS0tIFByZXBhcmUgdGhlIFVTQiBkcml2ZSAtLS0KICAgIFdyaXRlLUhvc3QgIlByZXBhcmluZyBVU0IgZHJpdmUgJHVzYlJvb3QgKGZvcm1hdHRpbmcgYXMgRkFUMzIpLi4uIgogICAgIyBVc2UgZGlza3BhcnQtZnJlZSBhcHByb2FjaDogZm9ybWF0IHZpYSBGb3JtYXQtVm9sdW1lLCB0aGVuIGJjZGJvb3QuCiAgICBGb3JtYXQtVm9sdW1lIC1Ecml2ZUxldHRlciAkRHJpdmVMZXR0ZXIgLUZpbGVTeXN0ZW0gRkFUMzIgLU5ld0ZpbGVTeXN0ZW1MYWJlbCAiRklMRUtFRVAiIC1Db25maXJtOiRmYWxzZSAtRm9yY2UKICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwIC1hbmQgJD8pIHsgV3JpdGUtSG9zdCAiRm9ybWF0IGNvbXBsZXRlLiIgfQoKICAgIFdyaXRlLUhvc3QgIkNvcHlpbmcgYm9vdCBmaWxlcy4uLiIKICAgIGJjZGJvb3QgQzpcV2luZG93cyAvcyAiJERyaXZlTGV0dGVyYDoiIC9mIFVFRkkKICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgImJjZGJvb3QgZmFpbGVkLiIgfQoKICAgIFdyaXRlLUhvc3QgIkNvcHlpbmcgY3VzdG9taXplZCBXaW5SRSBpbWFnZSB0byBVU0IuLi4iCiAgICAkdXNiU291cmNlcyA9IEpvaW4tUGF0aCAkdXNiUm9vdCAic291cmNlcyIKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICR1c2JTb3VyY2VzIHwgT3V0LU51bGwKICAgICMgQm9vdCBleHBlY3RzIGJvb3Qud2ltOyBwbGFjZSBvdXIgY3VzdG9taXplZCBpbWFnZSB0aGVyZS4KICAgIENvcHktSXRlbSAkd2ltQ29weSAoSm9pbi1QYXRoICR1c2JTb3VyY2VzICJib290LndpbSIpIC1Gb3JjZQoKICAgICMgQWxzbyBjb3B5IHRoZSBGaWxlS2VlcCB0b29scyB0byB0aGUgVVNCIHJvb3QgZm9yIGVhc3kgYWNjZXNzLgogICAgJHVzYkZrID0gSm9pbi1QYXRoICR1c2JSb290ICJGaWxlS2VlcCIKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICR1c2JGayB8IE91dC1OdWxsCiAgICBDb3B5LUl0ZW0gKEpvaW4tUGF0aCAkc3RhZ2VEaXIgIioiKSAkdXNiRmsgLVJlY3Vyc2UgLUZvcmNlCgogICAgV3JpdGUtSG9zdCAiVVNCIGJ1aWxkIGNvbXBsZXRlLiIKfSBmaW5hbGx5IHsKICAgICMgLS0tIFJlLWVuYWJsZSBXaW5SRSBvbiB0aGUgaG9zdCAtLS0KICAgIGlmICgtbm90ICRTa2lwUmVlbmFibGUgLWFuZCAkd2FzRW5hYmxlZCkgewogICAgICAgIFdyaXRlLUhvc3QgIlJlLWVuYWJsaW5nIFdpblJFLi4uIgogICAgICAgIHJlYWdlbnRjIC9lbmFibGUgfCBPdXQtTnVsbAogICAgICAgIGlmICgkTEFTVEVYSVRDT0RFIC1lcSAwKSB7CiAgICAgICAgICAgICR3aW5yZVJlZW5hYmxlZCA9ICR0cnVlCiAgICAgICAgICAgIFdyaXRlLUhvc3QgIldpblJFIHJlLWVuYWJsZWQuIgogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIFdyaXRlLVdhcm5pbmcgInJlYWdlbnRjIC9lbmFibGUgZmFpbGVkLiBSdW4gJ3JlYWdlbnRjIC9lbmFibGUnIG1hbnVhbGx5LiIKICAgICAgICB9CiAgICB9CiAgICAjIENsZWFudXAgdGVtcCBmaWxlcwogICAgUmVtb3ZlLUl0ZW0gJHN0YWdlRGlyIC1SZWN1cnNlIC1Gb3JjZSAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQogICAgJHdpbUNvcHkgPSBKb2luLVBhdGggKFtJTy5QYXRoXTo6R2V0VGVtcFBhdGgoKSkgImZpbGVrZWVwLXdpbnJlLndpbSIKICAgIFJlbW92ZS1JdGVtICR3aW1Db3B5IC1Gb3JjZSAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZQp9CgpXcml0ZS1Ib3N0ICIiCldyaXRlLUhvc3QgIj09PSBEb25lID09PSIKV3JpdGUtSG9zdCAiQm9vdGFibGUgRmlsZUtlZXAgcmVjb3ZlcnkgVVNCIGNyZWF0ZWQgb24gJHVzYlJvb3QiCmlmICgtbm90ICR3aW5yZVJlZW5hYmxlZCAtYW5kICR3YXNFbmFibGVkKSB7CiAgICBXcml0ZS1XYXJuaW5nICJXaW5SRSB3YXMgTk9UIHJlLWVuYWJsZWQgYXV0b21hdGljYWxseS4gUnVuICdyZWFnZW50YyAvZW5hYmxlJyBhcyBBZG1pbmlzdHJhdG9yLiIKfQo=
"@
[IO.File]::WriteAllBytes("C:\ub\src\install\UsenetBackup.wxs", [Convert]::FromBase64String($wxsB64))
[IO.File]::WriteAllBytes("C:\ub\src\winre\build-winre-usb.ps1", [Convert]::FromBase64String($winreB64))
Write-Host ("  UsenetBackup.wxs: {0:N0} bytes" -f (Get-Item C:\ub\src\install\UsenetBackup.wxs).Length)
Write-Host ("  build-winre-usb.ps1: {0:N0} bytes" -f (Get-Item C:\ub\src\winre\build-winre-usb.ps1).Length)

Write-Host "=== 2/6 Re-publishing apps as single-file ==="
# Single source root used consistently: the script cds here AND passes it to
# WiX as SrcRoot. (Previously these were two different hardcoded paths,
# Source root: use src-new if it exists (current VM layout), else src.
$srcRoot = if (Test-Path "C:\ub\src-new") { "C:\ub\src-new" } else { "C:\ub\src" }
cd $srcRoot
# Stamp file versions so Windows Installer replaces binaries on upgrade/reinstall.
# (Without this, every build carries the default FileVersion 1.0.0.0 and a
# reinstall silently keeps the previously installed binaries.)
# Build = days since 2026-01-01, revision = minutes since midnight: two builds
# on the same day still get distinct versions, so a same-day rebuild +
# reinstall actually replaces the binaries.
$now = Get-Date
$buildNo = [int](($now - (Get-Date "2026-01-01")).TotalDays)
$revNo = $now.Hour * 60 + $now.Minute
$fileVer = "0.8.$buildNo.$revNo"
$verProps = @("/p:Version=0.8.1", "/p:FileVersion=$fileVer",
              "/p:AssemblyVersion=0.8.1.0", "/p:InformationalVersion=0.8.1")
Write-Host "Stamping FileVersion $fileVer"
dotnet publish src/UsenetBackup.Cli/UsenetBackup.Cli.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\cli /p:PublishSingleFile=true @verProps
if ($LASTEXITCODE -ne 0) { throw "CLI publish failed" }
dotnet publish src/UsenetBackup.Service/UsenetBackup.Service.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\service /p:PublishSingleFile=true @verProps
if ($LASTEXITCODE -ne 0) { throw "Service publish failed" }
dotnet publish src/UsenetBackup.Recovery/UsenetBackup.Recovery.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\recovery /p:PublishSingleFile=true @verProps
if ($LASTEXITCODE -ne 0) { throw "Recovery publish failed" }

Write-Host "=== 3/6 Verifying required MSI payload files ==="
$required = @(
    "C:\ub\publish\cli\FileKeep.exe",
    "C:\ub\publish\service\FileKeepService.exe",
    "C:\ub\publish\recovery\FileKeepRecovery.exe"
)
foreach ($f in $required) {
    if (Test-Path $f) { Write-Host ("  OK: {0} ({1:N0} bytes)" -f $f, (Get-Item $f).Length) }
    else { throw "MISSING required MSI payload: $f" }
}

Write-Host "=== 4/6 Building MSI ==="
# Sign the executables BEFORE building the MSI so the signed binaries are packaged.
Write-Host "  Signing executables..."
Invoke-CodeSigning -Files @(
    "C:\ub\publish\cli\FileKeep.exe",
    "C:\ub\publish\service\FileKeepService.exe",
    "C:\ub\publish\recovery\FileKeepRecovery.exe"
)

# Build the VSS helper (MSVC or MinGW)
Write-Host "Building VSS helper..."
& "$srcRoot\src\UsenetBackup.VssHelper\build-vss-helper.ps1"
if ($LASTEXITCODE -ne 0) { throw "VSS helper build failed" }

wix build -arch x64 -d SrcRoot=$srcRoot -d CliBin=C:\ub\publish\cli -d ServiceBin=C:\ub\publish\service -d RecoveryBin=C:\ub\publish\recovery -d VssBin=$srcRoot\src\UsenetBackup.VssHelper -o C:\ub\filekeep-0.8.1.msi install/UsenetBackup.wxs
if ($LASTEXITCODE -ne 0) { throw "wix build failed" }
$msi = Get-Item C:\ub\filekeep-0.8.1.msi
Write-Host ("  MSI built: {0:N0} bytes" -f $msi.Length)

Write-Host "=== 5/6 Signing MSI ==="
Invoke-CodeSigning -Files @("C:\ub\filekeep-0.8.1.msi")

Write-Host "=== 6/6 Test install + verify + uninstall ==="
Start-Process msiexec -ArgumentList "/i", "C:\ub\filekeep-0.8.1.msi", "/qn" -Wait
Start-Sleep 15
foreach ($c in @("C:\Program Files\FileKeep\cli\FileKeep.exe",
                 "C:\Program Files\FileKeep\service\FileKeepService.exe",
                 "C:\Program Files\FileKeep\wizard\FileKeepRecovery.exe")) {
    if (Test-Path $c) { Write-Host "  OK installed: $c" } else { throw "MISSING after install: $c" }
}
$svc = sc.exe query FileKeep
Write-Host "  Service state:"
Write-Host $svc
if ($svc -notmatch "RUNNING") { Write-Host "  NOTE: service not running after install (expected: registered auto-start, starts on first boot / service start)" }

Write-Host "  Uninstalling..."
# Uninstall by ProductCode from the registered product (not by MSI path),
# because each build generates a new ProductCode.
$prods = @(Get-WmiObject Win32_Product | Where-Object { $_.Name -eq "FileKeep" })
if ($prods.Count -gt 0) {
    foreach ($prod in $prods) {
        Write-Host ("  Uninstalling product: {0}" -f $prod.IdentifyingNumber)
        Start-Process msiexec -ArgumentList "/x", $prod.IdentifyingNumber, "/qn" -Wait
        Start-Sleep 5
    }
    Start-Sleep 5
} else {
    Write-Host "  WARNING: FileKeep not found in Win32_Product, trying MSI path..."
    Start-Process msiexec -ArgumentList "/x", "C:\ub\filekeep-0.8.1.msi", "/qn" -Wait
    Start-Sleep 10
}
if (Test-Path "C:\Program Files\FileKeep") { throw "Uninstall left files behind" }
Write-Host "  Uninstall clean."

Write-Host ""
Write-Host "ALL DONE - MSI built, installed, verified, and uninstalled cleanly."
} finally {
    Stop-Transcript | Out-Null
}
