# Self-contained VM build for Usenet Backup.
# Embeds the fixed installer source + WinPE script (base64) so only ONE file
# needs to be transferred - no URLs to go stale.
#
# On the VM, run:
#   iwr "<this-script-url>" -OutFile C:\ub\run.ps1
#   C:\ub\run.ps1

$ErrorActionPreference = "Stop"

# Log everything to C:\ub\build.log: RDP drops do not kill the script on the
# VM, so if the session disconnects, reconnect and read the log for progress.
$transcript = "C:\ub\build.log"
try { Stop-Transcript | Out-Null } catch { }
Start-Transcript -Path $transcript -Append | Out-Null
Write-Host "Logging to $transcript"

try {

Write-Host "=== 1/5 Writing embedded installer source + WinPE script ==="
$wxsB64 = @"
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCEtLSBXaVggdjUgaW5zdGFsbGVyIGZvciBVc2VuZXQgQmFja3VwLgogICAgIFRoZSBhcHBzIHB1Ymxpc2ggYXMgc2luZ2xlLWZpbGUgZXhlY3V0YWJsZXMgKFB1Ymxpc2hTaW5nbGVGaWxlIGluIHRoZQogICAgIGNzcHJvaiksIHNvIHRoZSBwYXlsb2FkIGlzIGEgaGFuZGZ1bCBvZiBleHBsaWNpdCBmaWxlcyDigJQgbm8gaGFydmVzdGluZy4KICAgICBCdWlsZCBvbiBXaW5kb3dzIHdpdGggdGhlIFdpWCB2NSBkb3RuZXQgdG9vbDoKICAgICAgIHdpeCBidWlsZCAtYXJjaCB4NjQgLWQgU3JjUm9vdD1DOlx1YlxzcmMgLWQgQ2xpQmluPUM6XHViXHB1Ymxpc2hcY2xpIC1kIFNlcnZpY2VCaW49QzpcdWJccHVibGlzaFxzZXJ2aWNlIC1kIFJlY292ZXJ5QmluPUM6XHViXHB1Ymxpc2hccmVjb3ZlcnkgLW8gdXNlbmV0LWJhY2t1cC0wLjguMS14NjQubXNpIGluc3RhbGwvVXNlbmV0QmFja3VwLnd4cwogICAgIElNUE9SVEFOVDogcmUtcHVibGlzaCB3aXRoIHRoZSBjdXJyZW50IGNzcHJvaiAoc2luZ2xlLWZpbGUpIGJlZm9yZSBidWlsZGluZzsKICAgICB0aGUgTVNJIGluc3RhbGxzIG9ubHkgdGhlIGZpbGVzIGxpc3RlZCBiZWxvdy4KLS0+CjxXaXggeG1sbnM9Imh0dHA6Ly93aXh0b29sc2V0Lm9yZy9zY2hlbWFzL3Y0L3d4cyI+CiAgPFBhY2thZ2UgTmFtZT0iVXNlbmV0IEJhY2t1cCIKICAgICAgICAgICBWZXJzaW9uPSIwLjguMSIKICAgICAgICAgICBNYW51ZmFjdHVyZXI9IlVzZW5ldCBCYWNrdXAiCiAgICAgICAgICAgVXBncmFkZUNvZGU9IkY2RTBENkQxLTYxQTEtNDg0My04N0I5LTI4MjVBNDdBMThERCIKICAgICAgICAgICBTY29wZT0icGVyTWFjaGluZSI+CgogICAgPE1ham9yVXBncmFkZSBEb3duZ3JhZGVFcnJvck1lc3NhZ2U9IkEgbmV3ZXIgdmVyc2lvbiBvZiBVc2VuZXQgQmFja3VwIGlzIGFscmVhZHkgaW5zdGFsbGVkLiIgLz4KCiAgICA8TWVkaWEgSWQ9IjEiIENhYmluZXQ9InByb2R1Y3QuY2FiIiBFbWJlZENhYj0ieWVzIiAvPgoKICAgIDxTdGFuZGFyZERpcmVjdG9yeSBJZD0iUHJvZ3JhbUZpbGVzNjQzMkZvbGRlciI+CiAgICAgIDxEaXJlY3RvcnkgSWQ9IklOU1RBTExGT0xERVIiIE5hbWU9IlVzZW5ldEJhY2t1cCI+CiAgICAgICAgPERpcmVjdG9yeSBJZD0iQ0xJRElSIiBOYW1lPSJjbGkiIC8+CiAgICAgICAgPERpcmVjdG9yeSBJZD0iU0VSVklDRURJUiIgTmFtZT0ic2VydmljZSIgLz4KICAgICAgICA8RGlyZWN0b3J5IElkPSJXSVpBUkRESVIiIE5hbWU9IndpemFyZCIgLz4KICAgICAgPC9EaXJlY3Rvcnk+CiAgICA8L1N0YW5kYXJkRGlyZWN0b3J5PgoKICAgIDwhLS0gQ0xJIChzaW5nbGUtZmlsZSBleGU7IG5hdGl2ZSBTUUxpdGUgaXMgYnVuZGxlZCBpbnNpZGUpIC0tPgogICAgPENvbXBvbmVudEdyb3VwIElkPSJDbGlGaWxlcyIgRGlyZWN0b3J5PSJDTElESVIiPgogICAgICA8Q29tcG9uZW50IElkPSJDbGlFeGUiIEd1aWQ9IioiPgogICAgICAgIDxGaWxlIElkPSJDbGlFeGVGaWxlIiBTb3VyY2U9IiQodmFyLkNsaUJpbilcdXNlbmV0LWJhY2t1cC5leGUiIEtleVBhdGg9InllcyIgLz4KICAgICAgPC9Db21wb25lbnQ+CiAgICA8L0NvbXBvbmVudEdyb3VwPgoKICAgIDxDb21wb25lbnRHcm91cCBJZD0iU2VydmljZVJlZ2lzdHJhdGlvbiIgRGlyZWN0b3J5PSJTRVJWSUNFRElSIj4KICAgICAgPENvbXBvbmVudCBJZD0iU2VydmljZUV4ZWN1dGFibGUiPgogICAgICAgIDxGaWxlIElkPSJTZXJ2aWNlRXhlIiBTb3VyY2U9IiQodmFyLlNlcnZpY2VCaW4pXHVzZW5ldC1iYWNrdXAtc2VydmljZS5leGUiIEtleVBhdGg9InllcyIgLz4KICAgICAgICA8U2VydmljZUluc3RhbGwgSWQ9IkJhY2t1cFNlcnZpY2UiCiAgICAgICAgICAgICAgICAgICAgICAgIFR5cGU9Im93blByb2Nlc3MiCiAgICAgICAgICAgICAgICAgICAgICAgIE5hbWU9IlVzZW5ldEJhY2t1cCIKICAgICAgICAgICAgICAgICAgICAgICAgRGlzcGxheU5hbWU9IlVzZW5ldCBCYWNrdXAgU2VydmljZSIKICAgICAgICAgICAgICAgICAgICAgICAgRGVzY3JpcHRpb249IlNjaGVkdWxlZCBlbmNyeXB0ZWQgYmFja3VwcyB0byBVc2VuZXQuIgogICAgICAgICAgICAgICAgICAgICAgICBTdGFydD0iYXV0byIKICAgICAgICAgICAgICAgICAgICAgICAgQWNjb3VudD0iTG9jYWxTeXN0ZW0iCiAgICAgICAgICAgICAgICAgICAgICAgIEVycm9yQ29udHJvbD0ibm9ybWFsIiAvPgogICAgICAgIDxTZXJ2aWNlQ29udHJvbCBJZD0iQmFja3VwU2VydmljZUNvbnRyb2wiCiAgICAgICAgICAgICAgICAgICAgICAgIE5hbWU9IlVzZW5ldEJhY2t1cCIKICAgICAgICAgICAgICAgICAgICAgICAgU3RvcD0iYm90aCIKICAgICAgICAgICAgICAgICAgICAgICAgUmVtb3ZlPSJ1bmluc3RhbGwiCiAgICAgICAgICAgICAgICAgICAgICAgIFdhaXQ9InRydWUiIC8+CiAgICAgIDwvQ29tcG9uZW50PgogICAgPC9Db21wb25lbnRHcm91cD4KCiAgICA8IS0tIFJlY292ZXJ5IHdpemFyZCAoc2luZ2xlLWZpbGUgZXhlOyBuYXRpdmUgU1FMaXRlIGlzIGJ1bmRsZWQgaW5zaWRlKSAtLT4KICAgIDxDb21wb25lbnRHcm91cCBJZD0iUmVjb3ZlcnlGaWxlcyIgRGlyZWN0b3J5PSJXSVpBUkRESVIiPgogICAgICA8Q29tcG9uZW50IElkPSJSZWNvdmVyeUV4ZSIgR3VpZD0iKiI+CiAgICAgICAgPEZpbGUgSWQ9IlJlY292ZXJ5RXhlRmlsZSIgU291cmNlPSIkKHZhci5SZWNvdmVyeUJpbilcdXNlbmV0LWJhY2t1cC1yZWNvdmVyeS5leGUiIEtleVBhdGg9InllcyIgLz4KICAgICAgPC9Db21wb25lbnQ+CiAgICA8L0NvbXBvbmVudEdyb3VwPgoKICAgIDwhLS0gU2VydmljZSBjb25maWcgZXhhbXBsZSArIHJlY292ZXJ5IHJ1bmJvb2sgLS0+CiAgICA8Q29tcG9uZW50R3JvdXAgSWQ9IkRvY3MiIERpcmVjdG9yeT0iSU5TVEFMTEZPTERFUiI+CiAgICAgIDxDb21wb25lbnQgSWQ9IkRvY3NDb21wb25lbnQiIEd1aWQ9IjQzNjMxRjAwLTI2Q0ItNDZBNy1CRDhGLTM4REI0NEVDNEE1NCI+CiAgICAgICAgPEZpbGUgU291cmNlPSIkKHZhci5TcmNSb290KVxzcmNcVXNlbmV0QmFja3VwLlNlcnZpY2Vcc2VydmljZS5leGFtcGxlLmpzb24iIE5hbWU9InNlcnZpY2UuZXhhbXBsZS5qc29uIiAvPgogICAgICAgIDxGaWxlIFNvdXJjZT0iJCh2YXIuU3JjUm9vdClcZG9jc1xSRUNPVkVSWS5tZCIgTmFtZT0iUkVDT1ZFUlkubWQiIC8+CiAgICAgIDwvQ29tcG9uZW50PgogICAgPC9Db21wb25lbnRHcm91cD4KCiAgICA8RmVhdHVyZSBJZD0iUHJvZHVjdEZlYXR1cmUiIFRpdGxlPSJVc2VuZXQgQmFja3VwIiBMZXZlbD0iMSI+CiAgICAgIDxDb21wb25lbnRHcm91cFJlZiBJZD0iQ2xpRmlsZXMiIC8+CiAgICAgIDxDb21wb25lbnRHcm91cFJlZiBJZD0iU2VydmljZVJlZ2lzdHJhdGlvbiIgLz4KICAgICAgPENvbXBvbmVudEdyb3VwUmVmIElkPSJSZWNvdmVyeUZpbGVzIiAvPgogICAgICA8Q29tcG9uZW50R3JvdXBSZWYgSWQ9IkRvY3MiIC8+CiAgICA8L0ZlYXR1cmU+CiAgPC9QYWNrYWdlPgo8L1dpeD4K
"@
$winpeB64 = @"
IyBCdWlsZHMgYSBXaW5QRSBJU08gd2l0aCB0aGUgVXNlbmV0IEJhY2t1cCByZWNvdmVyeSB0b29s
cy4KIyBSdW4gb24gV2luZG93cyB3aXRoIHRoZSBBREsgKyBXaW5QRSBhZGQtb24gaW5zdGFsbGVk
LCBhcyBBZG1pbmlzdHJhdG9yLgojCiMgICAxLiBJbnN0YWxsIEFESyAoRGVwbG95bWVudCBUb29s
cykgKyBXaW5QRSBhZGQtb24gZnJvbQojICAgICAgaHR0cHM6Ly9sZWFybi5taWNyb3NvZnQuY29t
L2VuLXVzL3dpbmRvd3MtaGFyZHdhcmUvZ2V0LXN0YXJ0ZWQvYWRrLWluc3RhbGwvCiMgICAyLiBk
b3RuZXQgcHVibGlzaCB0aGUgQ0xJIGFuZCB3aXphcmQgKHNlbGYtY29udGFpbmVkLCB3aW4teDY0
KQojICAgMy4gUnVuIHRoaXMgc2NyaXB0OiAuXHdpbnBlXGJ1aWxkLXdpbnBlLnBzMSAtU291cmNl
RGlyIEM6XHViXHNyYwojCiMgT3V0cHV0OiBDOlx3aW5wZVx1c2VuZXQtYmFja3VwLXdpbnBlLmlz
bwoKcGFyYW0oCiAgICBbc3RyaW5nXSRTb3VyY2VEaXIgPSAiQzpcdWJcc3JjIiwKICAgIFtzdHJp
bmddJFdvcmtEaXIgPSAiQzpcd2lucGUiLAogICAgW3N0cmluZ10kU3RhZ2VEaXIgPSAiQzpcd2lu
cGUtc3RhZ2UiLAogICAgW3N0cmluZ10kSXNvUGF0aCA9ICJDOlx3aW5wZVx1c2VuZXQtYmFja3Vw
LXdpbnBlLmlzbyIKKQoKJEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJTdG9wIgoKZnVuY3Rpb24g
RmFpbCgkbXNnKSB7IFdyaXRlLUVycm9yICRtc2c7IGV4aXQgMSB9CgojIC0tLSBQcmVjb25kaXRp
b25zIC0tLQppZiAoLW5vdCAoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsXVtT
ZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0lkZW50aXR5XTo6R2V0Q3VycmVudCgpKS5Jc0luUm9s
ZShbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NCdWlsdEluUm9sZV06OkFkbWluaXN0cmF0b3Ip
KSB7CiAgICBGYWlsICJSdW4gYXMgQWRtaW5pc3RyYXRvci4iCn0KIyBUaGUgQURLIGluc3RhbGxl
ciBkb2VzIG5vdCBwdXQgRGVwbG95bWVudCBUb29scyBvbiBQQVRILCBhbmQgdGhlIHRvb2xzIGFy
ZQojIG5vdCBhbHdheXMgYXQgdGhlIHRleHRib29rIGxvY2F0aW9uLCBzbyBwcm9iZSB0aGUgc3Rh
bmRhcmQga2l0IGRpcnMsIHRoZW4KIyBQQVRILCB0aGVuIHNlYXJjaCB0aGUga2l0IHRyZWUgKHNt
YWxsKSBiZWZvcmUgZ2l2aW5nIHVwLgpmdW5jdGlvbiBGaW5kLUFka1Rvb2woW3N0cmluZ10kbmFt
ZSkgewogICAgJGNtZCA9IEdldC1Db21tYW5kICRuYW1lIC1FcnJvckFjdGlvbiBTaWxlbnRseUNv
bnRpbnVlCiAgICBpZiAoJGNtZCkgeyByZXR1cm4gJGNtZC5Tb3VyY2UgfQogICAgJGtpdFJvb3Rz
ID0gQCgKICAgICAgICAiQzpcUHJvZ3JhbSBGaWxlcyAoeDg2KVxXaW5kb3dzIEtpdHNcMTBcQXNz
ZXNzbWVudCBhbmQgRGVwbG95bWVudCBLaXQiLAogICAgICAgICJDOlxQcm9ncmFtIEZpbGVzXFdp
bmRvd3MgS2l0c1wxMFxBc3Nlc3NtZW50IGFuZCBEZXBsb3ltZW50IEtpdCIKICAgICkKICAgIGZv
cmVhY2ggKCRyb290IGluICRraXRSb290cykgewogICAgICAgICRwcm9iZSA9IEpvaW4tUGF0aCAk
cm9vdCAiRGVwbG95bWVudCBUb29sc1wkbmFtZSIKICAgICAgICBpZiAoVGVzdC1QYXRoICRwcm9i
ZSkgeyByZXR1cm4gJHByb2JlIH0KICAgIH0KICAgIGZvcmVhY2ggKCRyb290IGluICRraXRSb290
cykgewogICAgICAgIGlmIChUZXN0LVBhdGggJHJvb3QpIHsKICAgICAgICAgICAgJGZvdW5kID0g
R2V0LUNoaWxkSXRlbSAkcm9vdCAtRmlsdGVyICRuYW1lIC1SZWN1cnNlIC1FcnJvckFjdGlvbiBT
aWxlbnRseUNvbnRpbnVlIHwKICAgICAgICAgICAgICAgICAgICAgU2VsZWN0LU9iamVjdCAtRmly
c3QgMSAtRXhwYW5kUHJvcGVydHkgRnVsbE5hbWUKICAgICAgICAgICAgaWYgKCRmb3VuZCkgeyBy
ZXR1cm4gJGZvdW5kIH0KICAgICAgICB9CiAgICB9CiAgICByZXR1cm4gJG51bGwKfQpmb3JlYWNo
ICgkdG9vbCBpbiBAKCJjb3B5cGUuY21kIiwgIk1ha2VXaW5QRU1lZGlhLmNtZCIpKSB7CiAgICAk
dG9vbFBhdGggPSBGaW5kLUFka1Rvb2wgJHRvb2wKICAgIGlmICgtbm90ICR0b29sUGF0aCkgeyBG
YWlsICIkdG9vbCBub3QgZm91bmQuIEluc3RhbGwgQURLIERlcGxveW1lbnQgVG9vbHMgKyBXaW5Q
RSBhZGQtb24uIiB9CiAgICAkdG9vbERpciA9IFNwbGl0LVBhdGggJHRvb2xQYXRoCiAgICBpZiAo
JGVudjpQQVRIIC1ub3RsaWtlICIqJHRvb2xEaXIqIikgeyAkZW52OlBBVEggPSAiJHRvb2xEaXI7
JGVudjpQQVRIIiB9CiAgICBXcml0ZS1Ib3N0ICIkdG9vbCAtPiAkdG9vbFBhdGgiCn0KaWYgKC1u
b3QgKEdldC1Db21tYW5kIGRpc20uZXhlIC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSkg
eyBGYWlsICJkaXNtLmV4ZSBub3QgZm91bmQuIiB9CgojIC0tLSBQdWJsaXNoIHNlbGYtY29udGFp
bmVkIGJpbmFyaWVzIC0tLQojIE5PVEU6IHB1Ymxpc2ggaW50byBTdGFnZURpciwgTk9UIFdvcmtE
aXIg4oCUIFdvcmtEaXIgaXMgd2lwZWQgYmVsb3cgYnkgY29weXBlLgpXcml0ZS1Ib3N0ICJQdWJs
aXNoaW5nIENMSSBhbmQgcmVjb3Zlcnkgd2l6YXJkIChzZWxmLWNvbnRhaW5lZCB3aW4teDY0KS4u
LiIKJGNsaU91dCA9IEpvaW4tUGF0aCAkU3RhZ2VEaXIgImNsaSIKJHdpek91dCA9IEpvaW4tUGF0
aCAkU3RhZ2VEaXIgInJlY292ZXJ5Igpkb3RuZXQgcHVibGlzaCAoSm9pbi1QYXRoICRTb3VyY2VE
aXIgInNyY1xVc2VuZXRCYWNrdXAuQ2xpXFVzZW5ldEJhY2t1cC5DbGkuY3Nwcm9qIikgYAogICAg
LWMgUmVsZWFzZSAtciB3aW4teDY0IC0tc2VsZi1jb250YWluZWQgLW8gJGNsaU91dAppZiAoJExB
U1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJDTEkgcHVibGlzaCBmYWlsZWQuIiB9CmRvdG5ldCBw
dWJsaXNoIChKb2luLVBhdGggJFNvdXJjZURpciAic3JjXFVzZW5ldEJhY2t1cC5SZWNvdmVyeVxV
c2VuZXRCYWNrdXAuUmVjb3ZlcnkuY3Nwcm9qIikgYAogICAgLWMgUmVsZWFzZSAtciB3aW4teDY0
IC0tc2VsZi1jb250YWluZWQgLW8gJHdpek91dAppZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBG
YWlsICJXaXphcmQgcHVibGlzaCBmYWlsZWQuIiB9CgojIC0tLSBCdWlsZCBXaW5QRSBiYXNlIC0t
LQppZiAoVGVzdC1QYXRoICRXb3JrRGlyKSB7IFJlbW92ZS1JdGVtICRXb3JrRGlyIC1SZWN1cnNl
IC1Gb3JjZSB9CldyaXRlLUhvc3QgIlJ1bm5pbmcgY29weXBlLi4uIgpjb3B5cGUuY21kIGFtZDY0
ICRXb3JrRGlyCmlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgImNvcHlwZSBmYWlsZWQu
IiB9CgokbW91bnREaXIgPSBKb2luLVBhdGggJFdvcmtEaXIgIm1vdW50IgokYm9vdFdpbSA9IEpv
aW4tUGF0aCAkV29ya0RpciAibWVkaWFcc291cmNlc1xib290LndpbSIKCldyaXRlLUhvc3QgIk1v
dW50aW5nIGJvb3Qud2ltLi4uIgpkaXNtLmV4ZSAvTW91bnQtSW1hZ2UgL0ltYWdlRmlsZTokYm9v
dFdpbSAvaW5kZXg6MSAvTW91bnREaXI6JG1vdW50RGlyCmlmICgkTEFTVEVYSVRDT0RFIC1uZSAw
KSB7IEZhaWwgIkRJU00gbW91bnQgZmFpbGVkLiIgfQoKdHJ5IHsKICAgICMgLS0tIFdpblBFIG9w
dGlvbmFsIGNvbXBvbmVudHMgLS0tCiAgICAjIFRoZSB3aXphcmQncyBkcml2ZSBwaWNrZXIgdXNl
cyBXTUkgKFN5c3RlbS5NYW5hZ2VtZW50KTsgdGhlIGJhc2UgV2luUEUKICAgICMgaW1hZ2UgbWF5
IG5vdCBpbmNsdWRlIGl0LCBzbyBhZGQgdGhlIFdpblBFLVdNSSBwYWNrYWdlIHdoZW4gcHJlc2Vu
dC4KICAgICRvY0RpciA9ICJDOlxQcm9ncmFtIEZpbGVzICh4ODYpXFdpbmRvd3MgS2l0c1wxMFxB
c3Nlc3NtZW50IGFuZCBEZXBsb3ltZW50IEtpdFxXaW5kb3dzIFByZWluc3RhbGxhdGlvbiBFbnZp
cm9ubWVudFxhbWQ2NFxXaW5QRV9PQ3MiCiAgICAkd21pQ2FiID0gSm9pbi1QYXRoICRvY0RpciAi
V2luUEUtV01JLmNhYiIKICAgICR3bWlMYW5nID0gSm9pbi1QYXRoICRvY0RpciAiZW4tdXNcV2lu
UEUtV01JX2VuLXVzLmNhYiIKICAgIGlmIChUZXN0LVBhdGggJHdtaUNhYikgewogICAgICAgIFdy
aXRlLUhvc3QgIkFkZGluZyBXaW5QRS1XTUkgb3B0aW9uYWwgY29tcG9uZW50Li4uIgogICAgICAg
ICR3bWlBcmdzID0gQCgiL0FkZC1QYWNrYWdlIiwgIi9JbWFnZTokbW91bnREaXIiLCAiL1BhY2th
Z2VQYXRoOiR3bWlDYWIiKQogICAgICAgIGlmIChUZXN0LVBhdGggJHdtaUxhbmcpIHsgJHdtaUFy
Z3MgKz0gIi9QYWNrYWdlUGF0aDokd21pTGFuZyIgfQogICAgICAgICYgZGlzbS5leGUgQHdtaUFy
Z3MKICAgICAgICBpZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJESVNNIGFkZCBXaW5Q
RS1XTUkgZmFpbGVkLiIgfQogICAgfQogICAgZWxzZSB7CiAgICAgICAgV3JpdGUtSG9zdCAiV0FS
TklORzogV2luUEUtV01JLmNhYiBub3QgZm91bmQ7IHRoZSB3aXphcmQgZHJpdmUgcGlja2VyIG1h
eSBub3Qgd29yayBpbiBXaW5QRS4iCiAgICB9CgogICAgIyAtLS0gQWRkIHJlY292ZXJ5IHRvb2xz
IC0tLQogICAgJHRvb2xzRGlyID0gSm9pbi1QYXRoICRtb3VudERpciAidXNlbmV0LWJhY2t1cCIK
ICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICR0b29sc0RpciB8
IE91dC1OdWxsCiAgICBXcml0ZS1Ib3N0ICJDb3B5aW5nIENMSS4uLiIKICAgIENvcHktSXRlbSAo
Sm9pbi1QYXRoICRjbGlPdXQgIioiKSAkdG9vbHNEaXIgLVJlY3Vyc2UgLUZvcmNlCiAgICAkd2l6
YXJkRGlyID0gSm9pbi1QYXRoICR0b29sc0RpciAid2l6YXJkIgogICAgTmV3LUl0ZW0gLUl0ZW1U
eXBlIERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJHdpemFyZERpciB8IE91dC1OdWxsCiAgICBXcml0
ZS1Ib3N0ICJDb3B5aW5nIHdpemFyZC4uLiIKICAgIENvcHktSXRlbSAoSm9pbi1QYXRoICR3aXpP
dXQgIioiKSAkd2l6YXJkRGlyIC1SZWN1cnNlIC1Gb3JjZQogICAgV3JpdGUtSG9zdCAiQ29weWlu
ZyByZWNvdmVyeSBydW5ib29rLi4uIgogICAgQ29weS1JdGVtIChKb2luLVBhdGggJFNvdXJjZURp
ciAiZG9jc1xSRUNPVkVSWS5tZCIpICR0b29sc0RpciAtRm9yY2UKCiAgICAjIC0tLSBTdGFydHVw
IHNjcmlwdDogbmV0d29yayBpbml0ICsgbWVudSAtLS0KICAgICRzdGFydG5ldCA9IEAnCndwZWlu
aXQKQGVjaG8gb2ZmCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09CmVjaG8gIFVzZW5ldCBCYWNrdXAgUmVjb3ZlcnkgRW52aXJvbm1lbnQKZWNobyA9
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KZWNoby4KZWNo
byAgVG9vbHMgaW4gWDpcdXNlbmV0LWJhY2t1cFwgOgplY2hvICAgIHVzZW5ldC1iYWNrdXAuZXhl
ICAgICAgICAgICAoQ0xJKQplY2hvICAgIHdpemFyZFx1c2VuZXQtYmFja3VwLXJlY292ZXJ5LmV4
ZSAgKEdVSSB3aXphcmQpCmVjaG8gICAgUkVDT1ZFUlkubWQgICAgICAgICAgICAgICAgIChydW5i
b29rKQplY2hvLgplY2hvICBTdGFydCBuZXR3b3JraW5nIGlmIG5lZWRlZDogd3BlaW5pdAplY2hv
ICBMYXVuY2hpbmcgcmVjb3Zlcnkgd2l6YXJkLi4uCnN0YXJ0ICIiIFg6XHVzZW5ldC1iYWNrdXBc
d2l6YXJkXHVzZW5ldC1iYWNrdXAtcmVjb3ZlcnkuZXhlIC0td2luOTUKZWNoby4KY21kCidACiAg
ICAkc3RhcnRuZXQgfCBPdXQtRmlsZSAtRmlsZVBhdGggKEpvaW4tUGF0aCAkbW91bnREaXIgIldp
bmRvd3NcU3lzdGVtMzJcc3RhcnRuZXQuY21kIikgYAogICAgICAgIC1FbmNvZGluZyBhc2NpaSAt
Rm9yY2UKICAgIFdyaXRlLUhvc3QgInN0YXJ0bmV0LmNtZCB3cml0dGVuLiIKfQpmaW5hbGx5IHsK
ICAgIFdyaXRlLUhvc3QgIkNvbW1pdHRpbmcgYW5kIHVubW91bnRpbmcuLi4iCiAgICBkaXNtLmV4
ZSAvVW5tb3VudC1JbWFnZSAvTW91bnREaXI6JG1vdW50RGlyIC9Db21taXQKICAgIGlmICgkTEFT
VEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgIkRJU00gdW5tb3VudCBmYWlsZWQuIiB9Cn0KCiMgLS0t
IEJ1aWxkIElTTyAtLS0KV3JpdGUtSG9zdCAiQnVpbGRpbmcgSVNPLi4uIgpNYWtlV2luUEVNZWRp
YS5jbWQgL0lTTyAkV29ya0RpciAkSXNvUGF0aAppZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBG
YWlsICJNYWtlV2luUEVNZWRpYSBmYWlsZWQuIiB9CgpXcml0ZS1Ib3N0ICIiCldyaXRlLUhvc3Qg
IkRvbmU6ICRJc29QYXRoIgpXcml0ZS1Ib3N0ICJXcml0ZSBpdCB0byBVU0Igd2l0aCBSdWZ1cyAo
b3IgTWFrZVdpblBFTWVkaWEgL1VGRCkuIgo=
"@
[IO.File]::WriteAllBytes("C:\ub\src\install\UsenetBackup.wxs", [Convert]::FromBase64String($wxsB64))
[IO.File]::WriteAllBytes("C:\ub\src\winpe\build-winpe.ps1", [Convert]::FromBase64String($winpeB64))
Write-Host ("  UsenetBackup.wxs: {0:N0} bytes" -f (Get-Item C:\ub\src\install\UsenetBackup.wxs).Length)
Write-Host ("  build-winpe.ps1:  {0:N0} bytes" -f (Get-Item C:\ub\src\winpe\build-winpe.ps1).Length)

Write-Host "=== 2/5 Re-publishing apps as single-file ==="
# Single source root used consistently: the script cds here AND passes it to
# WiX as SrcRoot. (Previously these were two different hardcoded paths,
# forcing a manual copy to both locations.)
$srcRoot = "C:\ub\src"
cd $srcRoot
# Stamp file versions so Windows Installer replaces binaries on upgrade/reinstall.
# (Without this, every build carries the default FileVersion 1.0.0.0 and a
# reinstall silently keeps the previously installed binaries.)
# Build = days since 2026-01-01, revision = minutes since midnight: two builds
# on the same day still get distinct versions, so a same-day rebuild +
# reinstall actually replaces the binaries.
$now = Get-Date
$buildNo = [int](($now - (Get-Date "2026-01-01")).TotalDays)
$revNo = $now.Hour * 60 + $now.Minute
$fileVer = "0.8.$buildNo.$revNo"
$verProps = @("/p:Version=0.8.1", "/p:FileVersion=$fileVer",
              "/p:AssemblyVersion=0.8.1.0", "/p:InformationalVersion=0.8.1")
Write-Host "Stamping FileVersion $fileVer"
dotnet publish src/UsenetBackup.Cli/UsenetBackup.Cli.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\cli /p:PublishSingleFile=true @verProps
if ($LASTEXITCODE -ne 0) { throw "CLI publish failed" }
dotnet publish src/UsenetBackup.Service/UsenetBackup.Service.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\service /p:PublishSingleFile=true @verProps
if ($LASTEXITCODE -ne 0) { throw "Service publish failed" }
dotnet publish src/UsenetBackup.Recovery/UsenetBackup.Recovery.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\recovery /p:PublishSingleFile=true @verProps
if ($LASTEXITCODE -ne 0) { throw "Recovery publish failed" }

Write-Host "=== 3/5 Verifying required MSI payload files ==="
$required = @(
    "C:\ub\publish\cli\usenet-backup.exe",
    "C:\ub\publish\service\usenet-backup-service.exe",
    "C:\ub\publish\recovery\usenet-backup-recovery.exe"
)
foreach ($f in $required) {
    if (Test-Path $f) { Write-Host ("  OK: {0} ({1:N0} bytes)" -f $f, (Get-Item $f).Length) }
    else { throw "MISSING required MSI payload: $f" }
}

Write-Host "=== 4/5 Building MSI ==="
wix build -arch x64 -d SrcRoot=$srcRoot -d CliBin=C:\ub\publish\cli -d ServiceBin=C:\ub\publish\service -d RecoveryBin=C:\ub\publish\recovery -o C:\ub\usenet-backup-0.8.1-x64.msi install/UsenetBackup.wxs
if ($LASTEXITCODE -ne 0) { throw "wix build failed" }
$msi = Get-Item C:\ub\usenet-backup-0.8.1-x64.msi
Write-Host ("  MSI built: {0:N0} bytes" -f $msi.Length)

Write-Host "=== 5/5 Test install + verify + uninstall ==="
Start-Process msiexec -ArgumentList "/i", "C:\ub\usenet-backup-0.8.1-x64.msi", "/qn" -Wait
Start-Sleep 15
foreach ($c in @("C:\Program Files\UsenetBackup\cli\usenet-backup.exe",
                 "C:\Program Files\UsenetBackup\service\usenet-backup-service.exe",
                 "C:\Program Files\UsenetBackup\wizard\usenet-backup-recovery.exe")) {
    if (Test-Path $c) { Write-Host "  OK installed: $c" } else { throw "MISSING after install: $c" }
}
$svc = sc.exe query UsenetBackup
Write-Host "  Service state:"
Write-Host $svc
if ($svc -notmatch "RUNNING") { Write-Host "  NOTE: service not running after install (expected: registered auto-start, starts on first boot / service start)" }

Write-Host "  Uninstalling..."
Start-Process msiexec -ArgumentList "/x", "C:\ub\usenet-backup-0.8.1-x64.msi", "/qn" -Wait
Start-Sleep 10
if (Test-Path "C:\Program Files\UsenetBackup") { throw "Uninstall left files behind" }
Write-Host "  Uninstall clean."

Write-Host ""
Write-Host "ALL DONE - MSI built, installed, verified, and uninstalled cleanly."
} finally {
    Stop-Transcript | Out-Null
}
