# Self-contained VM build for Usenet Backup.
# Embeds the fixed installer source + WinPE script (base64) so only ONE file
# needs to be transferred - no URLs to go stale.
#
# On the VM, run:
#   iwr "<this-script-url>" -OutFile C:\ub\run.ps1
#   C:\ub\run.ps1

$ErrorActionPreference = "Stop"

Write-Host "=== 1/5 Writing embedded installer source + WinPE script ==="
$wxsB64 = @"
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCEtLSBXaVggdjUgaW5zdGFsbGVyIGZvciBVc2VuZXQgQmFj
a3VwLgogICAgIFRoZSBhcHBzIHB1Ymxpc2ggYXMgc2luZ2xlLWZpbGUgZXhlY3V0YWJsZXMgKFB1Ymxpc2hTaW5nbGVGaWxlIGlu
IHRoZQogICAgIGNzcHJvaiksIHNvIHRoZSBwYXlsb2FkIGlzIGEgaGFuZGZ1bCBvZiBleHBsaWNpdCBmaWxlcyDigJQgbm8gaGFy
dmVzdGluZy4KICAgICBCdWlsZCBvbiBXaW5kb3dzIHdpdGggdGhlIFdpWCB2NSBkb3RuZXQgdG9vbDoKICAgICAgIHdpeCBidWls
ZCAtYXJjaCB4NjQgLWQgQ2xpQmluPUM6XHViXHB1Ymxpc2hcY2xpIC1kIFNlcnZpY2VCaW49QzpcdWJccHVibGlzaFxzZXJ2aWNl
IC1kIFJlY292ZXJ5QmluPUM6XHViXHB1Ymxpc2hccmVjb3ZlcnkgLW8gdXNlbmV0LWJhY2t1cC0wLjguMC14NjQubXNpIGluc3Rh
bGwvVXNlbmV0QmFja3VwLnd4cwogICAgIElNUE9SVEFOVDogcmUtcHVibGlzaCB3aXRoIHRoZSBjdXJyZW50IGNzcHJvaiAoc2lu
Z2xlLWZpbGUpIGJlZm9yZSBidWlsZGluZzsKICAgICB0aGUgTVNJIGluc3RhbGxzIG9ubHkgdGhlIGZpbGVzIGxpc3RlZCBiZWxv
dy4KLS0+CjxXaXggeG1sbnM9Imh0dHA6Ly93aXh0b29sc2V0Lm9yZy9zY2hlbWFzL3Y0L3d4cyI+CiAgPFBhY2thZ2UgTmFtZT0i
VXNlbmV0IEJhY2t1cCIKICAgICAgICAgICBWZXJzaW9uPSIwLjguMCIKICAgICAgICAgICBNYW51ZmFjdHVyZXI9IlVzZW5ldCBC
YWNrdXAiCiAgICAgICAgICAgVXBncmFkZUNvZGU9IkY2RTBENkQxLTYxQTEtNDg0My04N0I5LTI4MjVBNDdBMThERCI+CgogICAg
PE1ham9yVXBncmFkZSBEb3duZ3JhZGVFcnJvck1lc3NhZ2U9IkEgbmV3ZXIgdmVyc2lvbiBvZiBVc2VuZXQgQmFja3VwIGlzIGFs
cmVhZHkgaW5zdGFsbGVkLiIgLz4KCiAgICA8U3RhbmRhcmREaXJlY3RvcnkgSWQ9IlByb2dyYW1GaWxlczY0MzJGb2xkZXIiPgog
ICAgICA8RGlyZWN0b3J5IElkPSJJTlNUQUxMRk9MREVSIiBOYW1lPSJVc2VuZXRCYWNrdXAiPgogICAgICAgIDxEaXJlY3Rvcnkg
SWQ9IkNMSURJUiIgTmFtZT0iY2xpIiAvPgogICAgICAgIDxEaXJlY3RvcnkgSWQ9IlNFUlZJQ0VESVIiIE5hbWU9InNlcnZpY2Ui
IC8+CiAgICAgICAgPERpcmVjdG9yeSBJZD0iV0laQVJERElSIiBOYW1lPSJ3aXphcmQiIC8+CiAgICAgIDwvRGlyZWN0b3J5Pgog
ICAgPC9TdGFuZGFyZERpcmVjdG9yeT4KCiAgICA8IS0tIENMSSAoc2luZ2xlLWZpbGUgZXhlOyBuYXRpdmUgU1FMaXRlIGlzIGJ1
bmRsZWQgaW5zaWRlKSAtLT4KICAgIDxDb21wb25lbnRHcm91cCBJZD0iQ2xpRmlsZXMiIERpcmVjdG9yeT0iQ0xJRElSIj4KICAg
ICAgPENvbXBvbmVudCBJZD0iQ2xpRXhlIiBHdWlkPSIqIj4KICAgICAgICA8RmlsZSBJZD0iQ2xpRXhlRmlsZSIgU291cmNlPSIk
KHZhci5DbGlCaW4pXHVzZW5ldC1iYWNrdXAuZXhlIiBLZXlQYXRoPSJ5ZXMiIC8+CiAgICAgIDwvQ29tcG9uZW50PgogICAgPC9D
b21wb25lbnRHcm91cD4KCiAgICA8Q29tcG9uZW50R3JvdXAgSWQ9IlNlcnZpY2VSZWdpc3RyYXRpb24iIERpcmVjdG9yeT0iU0VS
VklDRURJUiI+CiAgICAgIDxDb21wb25lbnQgSWQ9IlNlcnZpY2VFeGVjdXRhYmxlIj4KICAgICAgICA8RmlsZSBJZD0iU2Vydmlj
ZUV4ZSIgU291cmNlPSIkKHZhci5TZXJ2aWNlQmluKVx1c2VuZXQtYmFja3VwLXNlcnZpY2UuZXhlIiBLZXlQYXRoPSJ5ZXMiIC8+
CiAgICAgICAgPFNlcnZpY2VJbnN0YWxsIElkPSJCYWNrdXBTZXJ2aWNlIgogICAgICAgICAgICAgICAgICAgICAgICBUeXBlPSJv
d25Qcm9jZXNzIgogICAgICAgICAgICAgICAgICAgICAgICBOYW1lPSJVc2VuZXRCYWNrdXAiCiAgICAgICAgICAgICAgICAgICAg
ICAgIERpc3BsYXlOYW1lPSJVc2VuZXQgQmFja3VwIFNlcnZpY2UiCiAgICAgICAgICAgICAgICAgICAgICAgIERlc2NyaXB0aW9u
PSJTY2hlZHVsZWQgZW5jcnlwdGVkIGJhY2t1cHMgdG8gVXNlbmV0LiIKICAgICAgICAgICAgICAgICAgICAgICAgU3RhcnQ9ImF1
dG8iCiAgICAgICAgICAgICAgICAgICAgICAgIEFjY291bnQ9IkxvY2FsU3lzdGVtIgogICAgICAgICAgICAgICAgICAgICAgICBF
cnJvckNvbnRyb2w9Im5vcm1hbCIgLz4KICAgICAgICA8U2VydmljZUNvbnRyb2wgSWQ9IkJhY2t1cFNlcnZpY2VDb250cm9sIgog
ICAgICAgICAgICAgICAgICAgICAgICBOYW1lPSJVc2VuZXRCYWNrdXAiCiAgICAgICAgICAgICAgICAgICAgICAgIFN0YXJ0PSJp
bnN0YWxsIgogICAgICAgICAgICAgICAgICAgICAgICBTdG9wPSJib3RoIgogICAgICAgICAgICAgICAgICAgICAgICBSZW1vdmU9
InVuaW5zdGFsbCIKICAgICAgICAgICAgICAgICAgICAgICAgV2FpdD0idHJ1ZSIgLz4KICAgICAgPC9Db21wb25lbnQ+CiAgICA8
L0NvbXBvbmVudEdyb3VwPgoKICAgIDwhLS0gUmVjb3Zlcnkgd2l6YXJkIChzaW5nbGUtZmlsZSBleGU7IG5hdGl2ZSBTUUxpdGUg
aXMgYnVuZGxlZCBpbnNpZGUpIC0tPgogICAgPENvbXBvbmVudEdyb3VwIElkPSJSZWNvdmVyeUZpbGVzIiBEaXJlY3Rvcnk9IldJ
WkFSRERJUiI+CiAgICAgIDxDb21wb25lbnQgSWQ9IlJlY292ZXJ5RXhlIiBHdWlkPSIqIj4KICAgICAgICA8RmlsZSBJZD0iUmVj
b3ZlcnlFeGVGaWxlIiBTb3VyY2U9IiQodmFyLlJlY292ZXJ5QmluKVx1c2VuZXQtYmFja3VwLXJlY292ZXJ5LmV4ZSIgS2V5UGF0
aD0ieWVzIiAvPgogICAgICA8L0NvbXBvbmVudD4KICAgIDwvQ29tcG9uZW50R3JvdXA+CgogICAgPCEtLSBTZXJ2aWNlIGNvbmZp
ZyBleGFtcGxlICsgcmVjb3ZlcnkgcnVuYm9vayAtLT4KICAgIDxDb21wb25lbnRHcm91cCBJZD0iRG9jcyIgRGlyZWN0b3J5PSJJ
TlNUQUxMRk9MREVSIj4KICAgICAgPENvbXBvbmVudCBJZD0iRG9jc0NvbXBvbmVudCIgR3VpZD0iNDM2MzFGMDAtMjZDQi00NkE3
LUJEOEYtMzhEQjQ0RUM0QTU0Ij4KICAgICAgICA8RmlsZSBTb3VyY2U9InNyYy9Vc2VuZXRCYWNrdXAuU2VydmljZS9zZXJ2aWNl
LmV4YW1wbGUuanNvbiIgTmFtZT0ic2VydmljZS5leGFtcGxlLmpzb24iIC8+CiAgICAgICAgPEZpbGUgU291cmNlPSJkb2NzL1JF
Q09WRVJZLm1kIiBOYW1lPSJSRUNPVkVSWS5tZCIgLz4KICAgICAgPC9Db21wb25lbnQ+CiAgICA8L0NvbXBvbmVudEdyb3VwPgoK
ICAgIDxGZWF0dXJlIElkPSJQcm9kdWN0RmVhdHVyZSIgVGl0bGU9IlVzZW5ldCBCYWNrdXAiIExldmVsPSIxIj4KICAgICAgPENv
bXBvbmVudEdyb3VwUmVmIElkPSJDbGlGaWxlcyIgLz4KICAgICAgPENvbXBvbmVudEdyb3VwUmVmIElkPSJTZXJ2aWNlUmVnaXN0
cmF0aW9uIiAvPgogICAgICA8Q29tcG9uZW50R3JvdXBSZWYgSWQ9IlJlY292ZXJ5RmlsZXMiIC8+CiAgICAgIDxDb21wb25lbnRH
cm91cFJlZiBJZD0iRG9jcyIgLz4KICAgIDwvRmVhdHVyZT4KICA8L1BhY2thZ2U+CjwvV2l4Pgo=
"@
$winpeB64 = @"
IyBCdWlsZHMgYSBXaW5QRSBJU08gd2l0aCB0aGUgVXNlbmV0IEJhY2t1cCByZWNvdmVyeSB0b29scy4KIyBSdW4gb24gV2luZG93
cyB3aXRoIHRoZSBBREsgKyBXaW5QRSBhZGQtb24gaW5zdGFsbGVkLCBhcyBBZG1pbmlzdHJhdG9yLgojCiMgICAxLiBJbnN0YWxs
IEFESyAoRGVwbG95bWVudCBUb29scykgKyBXaW5QRSBhZGQtb24gZnJvbQojICAgICAgaHR0cHM6Ly9sZWFybi5taWNyb3NvZnQu
Y29tL2VuLXVzL3dpbmRvd3MtaGFyZHdhcmUvZ2V0LXN0YXJ0ZWQvYWRrLWluc3RhbGwvCiMgICAyLiBkb3RuZXQgcHVibGlzaCB0
aGUgQ0xJIGFuZCB3aXphcmQgKHNlbGYtY29udGFpbmVkLCB3aW4teDY0KQojICAgMy4gUnVuIHRoaXMgc2NyaXB0OiAuXHdpbnBl
XGJ1aWxkLXdpbnBlLnBzMSAtU291cmNlRGlyIEM6XHViXHNyYwojCiMgT3V0cHV0OiBDOlx3aW5wZVx1c2VuZXQtYmFja3VwLXdp
bnBlLmlzbwoKcGFyYW0oCiAgICBbc3RyaW5nXSRTb3VyY2VEaXIgPSAiQzpcdWJcc3JjIiwKICAgIFtzdHJpbmddJFdvcmtEaXIg
PSAiQzpcd2lucGUiLAogICAgW3N0cmluZ10kU3RhZ2VEaXIgPSAiQzpcd2lucGUtc3RhZ2UiLAogICAgW3N0cmluZ10kSXNvUGF0
aCA9ICJDOlx3aW5wZVx1c2VuZXQtYmFja3VwLXdpbnBlLmlzbyIKKQoKJEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJTdG9wIgoK
ZnVuY3Rpb24gRmFpbCgkbXNnKSB7IFdyaXRlLUVycm9yICRtc2c7IGV4aXQgMSB9CgojIC0tLSBQcmVjb25kaXRpb25zIC0tLQpp
ZiAoLW5vdCAoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsXVtTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0lk
ZW50aXR5XTo6R2V0Q3VycmVudCgpKS5Jc0luUm9sZShbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NCdWlsdEluUm9sZV06OkFk
bWluaXN0cmF0b3IpKSB7CiAgICBGYWlsICJSdW4gYXMgQWRtaW5pc3RyYXRvci4iCn0KZm9yZWFjaCAoJHRvb2wgaW4gQCgiY29w
eXBlLmNtZCIsICJNYWtlV2luUEVNZWRpYS5jbWQiKSkgewogICAgaWYgKC1ub3QgKEdldC1Db21tYW5kICR0b29sIC1FcnJvckFj
dGlvbiBTaWxlbnRseUNvbnRpbnVlKSkgeyBGYWlsICIkdG9vbCBub3QgZm91bmQuIEluc3RhbGwgQURLIERlcGxveW1lbnQgVG9v
bHMgKyBXaW5QRSBhZGQtb24uIiB9Cn0KaWYgKC1ub3QgKEdldC1Db21tYW5kIGRpc20uZXhlIC1FcnJvckFjdGlvbiBTaWxlbnRs
eUNvbnRpbnVlKSkgeyBGYWlsICJkaXNtLmV4ZSBub3QgZm91bmQuIiB9CgojIC0tLSBQdWJsaXNoIHNlbGYtY29udGFpbmVkIGJp
bmFyaWVzIC0tLQojIE5PVEU6IHB1Ymxpc2ggaW50byBTdGFnZURpciwgTk9UIFdvcmtEaXIg4oCUIFdvcmtEaXIgaXMgd2lwZWQg
YmVsb3cgYnkgY29weXBlLgpXcml0ZS1Ib3N0ICJQdWJsaXNoaW5nIENMSSBhbmQgcmVjb3Zlcnkgd2l6YXJkIChzZWxmLWNvbnRh
aW5lZCB3aW4teDY0KS4uLiIKJGNsaU91dCA9IEpvaW4tUGF0aCAkU3RhZ2VEaXIgImNsaSIKJHdpek91dCA9IEpvaW4tUGF0aCAk
U3RhZ2VEaXIgInJlY292ZXJ5Igpkb3RuZXQgcHVibGlzaCAoSm9pbi1QYXRoICRTb3VyY2VEaXIgInNyY1xVc2VuZXRCYWNrdXAu
Q2xpXFVzZW5ldEJhY2t1cC5DbGkuY3Nwcm9qIikgYAogICAgLWMgUmVsZWFzZSAtciB3aW4teDY0IC0tc2VsZi1jb250YWluZWQg
LW8gJGNsaU91dAppZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJDTEkgcHVibGlzaCBmYWlsZWQuIiB9CmRvdG5ldCBw
dWJsaXNoIChKb2luLVBhdGggJFNvdXJjZURpciAic3JjXFVzZW5ldEJhY2t1cC5SZWNvdmVyeVxVc2VuZXRCYWNrdXAuUmVjb3Zl
cnkuY3Nwcm9qIikgYAogICAgLWMgUmVsZWFzZSAtciB3aW4teDY0IC0tc2VsZi1jb250YWluZWQgLW8gJHdpek91dAppZiAoJExB
U1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJXaXphcmQgcHVibGlzaCBmYWlsZWQuIiB9CgojIC0tLSBCdWlsZCBXaW5QRSBiYXNl
IC0tLQppZiAoVGVzdC1QYXRoICRXb3JrRGlyKSB7IFJlbW92ZS1JdGVtICRXb3JrRGlyIC1SZWN1cnNlIC1Gb3JjZSB9CldyaXRl
LUhvc3QgIlJ1bm5pbmcgY29weXBlLi4uIgpjb3B5cGUuY21kIGFtZDY0ICRXb3JrRGlyCmlmICgkTEFTVEVYSVRDT0RFIC1uZSAw
KSB7IEZhaWwgImNvcHlwZSBmYWlsZWQuIiB9CgokbW91bnREaXIgPSBKb2luLVBhdGggJFdvcmtEaXIgIm1vdW50IgokYm9vdFdp
bSA9IEpvaW4tUGF0aCAkV29ya0RpciAibWVkaWFcc291cmNlc1xib290LndpbSIKCldyaXRlLUhvc3QgIk1vdW50aW5nIGJvb3Qu
d2ltLi4uIgpkaXNtLmV4ZSAvTW91bnQtSW1hZ2UgL0ltYWdlRmlsZTokYm9vdFdpbSAvaW5kZXg6MSAvTW91bnREaXI6JG1vdW50
RGlyCmlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgIkRJU00gbW91bnQgZmFpbGVkLiIgfQoKdHJ5IHsKICAgICMgLS0t
IFdpblBFIG9wdGlvbmFsIGNvbXBvbmVudHMgLS0tCiAgICAjIFRoZSB3aXphcmQncyBkcml2ZSBwaWNrZXIgdXNlcyBXTUkgKFN5
c3RlbS5NYW5hZ2VtZW50KTsgdGhlIGJhc2UgV2luUEUKICAgICMgaW1hZ2UgbWF5IG5vdCBpbmNsdWRlIGl0LCBzbyBhZGQgdGhl
IFdpblBFLVdNSSBwYWNrYWdlIHdoZW4gcHJlc2VudC4KICAgICRvY0RpciA9ICJDOlxQcm9ncmFtIEZpbGVzICh4ODYpXFdpbmRv
d3MgS2l0c1wxMFxBc3Nlc3NtZW50IGFuZCBEZXBsb3ltZW50IEtpdFxXaW5kb3dzIFByZWluc3RhbGxhdGlvbiBFbnZpcm9ubWVu
dFxhbWQ2NFxXaW5QRV9PQ3MiCiAgICAkd21pQ2FiID0gSm9pbi1QYXRoICRvY0RpciAiV2luUEUtV01JLmNhYiIKICAgICR3bWlM
YW5nID0gSm9pbi1QYXRoICRvY0RpciAiZW4tdXNcV2luUEUtV01JX2VuLXVzLmNhYiIKICAgIGlmIChUZXN0LVBhdGggJHdtaUNh
YikgewogICAgICAgIFdyaXRlLUhvc3QgIkFkZGluZyBXaW5QRS1XTUkgb3B0aW9uYWwgY29tcG9uZW50Li4uIgogICAgICAgICR3
bWlBcmdzID0gQCgiL0FkZC1QYWNrYWdlIiwgIi9JbWFnZTokbW91bnREaXIiLCAiL1BhY2thZ2VQYXRoOiR3bWlDYWIiKQogICAg
ICAgIGlmIChUZXN0LVBhdGggJHdtaUxhbmcpIHsgJHdtaUFyZ3MgKz0gIi9QYWNrYWdlUGF0aDokd21pTGFuZyIgfQogICAgICAg
ICYgZGlzbS5leGUgQHdtaUFyZ3MKICAgICAgICBpZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJESVNNIGFkZCBXaW5Q
RS1XTUkgZmFpbGVkLiIgfQogICAgfQogICAgZWxzZSB7CiAgICAgICAgV3JpdGUtSG9zdCAiV0FSTklORzogV2luUEUtV01JLmNh
YiBub3QgZm91bmQ7IHRoZSB3aXphcmQgZHJpdmUgcGlja2VyIG1heSBub3Qgd29yayBpbiBXaW5QRS4iCiAgICB9CgogICAgIyAt
LS0gQWRkIHJlY292ZXJ5IHRvb2xzIC0tLQogICAgJHRvb2xzRGlyID0gSm9pbi1QYXRoICRtb3VudERpciAidXNlbmV0LWJhY2t1
cCIKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICR0b29sc0RpciB8IE91dC1OdWxsCiAgICBX
cml0ZS1Ib3N0ICJDb3B5aW5nIENMSS4uLiIKICAgIENvcHktSXRlbSAoSm9pbi1QYXRoICRjbGlPdXQgIioiKSAkdG9vbHNEaXIg
LVJlY3Vyc2UgLUZvcmNlCiAgICAkd2l6YXJkRGlyID0gSm9pbi1QYXRoICR0b29sc0RpciAid2l6YXJkIgogICAgTmV3LUl0ZW0g
LUl0ZW1UeXBlIERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJHdpemFyZERpciB8IE91dC1OdWxsCiAgICBXcml0ZS1Ib3N0ICJDb3B5
aW5nIHdpemFyZC4uLiIKICAgIENvcHktSXRlbSAoSm9pbi1QYXRoICR3aXpPdXQgIioiKSAkd2l6YXJkRGlyIC1SZWN1cnNlIC1G
b3JjZQogICAgV3JpdGUtSG9zdCAiQ29weWluZyByZWNvdmVyeSBydW5ib29rLi4uIgogICAgQ29weS1JdGVtIChKb2luLVBhdGgg
JFNvdXJjZURpciAiZG9jc1xSRUNPVkVSWS5tZCIpICR0b29sc0RpciAtRm9yY2UKCiAgICAjIC0tLSBTdGFydHVwIHNjcmlwdDog
bmV0d29yayBpbml0ICsgbWVudSAtLS0KICAgICRzdGFydG5ldCA9IEAnCndwZWluaXQKQGVjaG8gb2ZmCmVjaG8gPT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CmVjaG8gIFVzZW5ldCBCYWNrdXAgUmVjb3ZlcnkgRW52aXJv
bm1lbnQKZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KZWNoby4KZWNobyAgVG9v
bHMgaW4gWDpcdXNlbmV0LWJhY2t1cFwgOgplY2hvICAgIHVzZW5ldC1iYWNrdXAuZXhlICAgICAgICAgICAoQ0xJKQplY2hvICAg
IHdpemFyZFx1c2VuZXQtYmFja3VwLXJlY292ZXJ5LmV4ZSAgKEdVSSB3aXphcmQpCmVjaG8gICAgUkVDT1ZFUlkubWQgICAgICAg
ICAgICAgICAgIChydW5ib29rKQplY2hvLgplY2hvICBTdGFydCBuZXR3b3JraW5nIGlmIG5lZWRlZDogd3BlaW5pdAplY2hvICBM
YXVuY2hpbmcgcmVjb3Zlcnkgd2l6YXJkLi4uCnN0YXJ0ICIiIFg6XHVzZW5ldC1iYWNrdXBcd2l6YXJkXHVzZW5ldC1iYWNrdXAt
cmVjb3ZlcnkuZXhlIC0td2luOTUKZWNoby4KY21kCidACiAgICAkc3RhcnRuZXQgfCBPdXQtRmlsZSAtRmlsZVBhdGggKEpvaW4t
UGF0aCAkbW91bnREaXIgIldpbmRvd3NcU3lzdGVtMzJcc3RhcnRuZXQuY21kIikgYAogICAgICAgIC1FbmNvZGluZyBhc2NpaSAt
Rm9yY2UKICAgIFdyaXRlLUhvc3QgInN0YXJ0bmV0LmNtZCB3cml0dGVuLiIKfQpmaW5hbGx5IHsKICAgIFdyaXRlLUhvc3QgIkNv
bW1pdHRpbmcgYW5kIHVubW91bnRpbmcuLi4iCiAgICBkaXNtLmV4ZSAvVW5tb3VudC1JbWFnZSAvTW91bnREaXI6JG1vdW50RGly
IC9Db21taXQKICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7IEZhaWwgIkRJU00gdW5tb3VudCBmYWlsZWQuIiB9Cn0KCiMg
LS0tIEJ1aWxkIElTTyAtLS0KV3JpdGUtSG9zdCAiQnVpbGRpbmcgSVNPLi4uIgpNYWtlV2luUEVNZWRpYS5jbWQgL0lTTyAkV29y
a0RpciAkSXNvUGF0aAppZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgeyBGYWlsICJNYWtlV2luUEVNZWRpYSBmYWlsZWQuIiB9CgpX
cml0ZS1Ib3N0ICIiCldyaXRlLUhvc3QgIkRvbmU6ICRJc29QYXRoIgpXcml0ZS1Ib3N0ICJXcml0ZSBpdCB0byBVU0Igd2l0aCBS
dWZ1cyAob3IgTWFrZVdpblBFTWVkaWEgL1VGRCkuIgo=
"@
[IO.File]::WriteAllBytes("C:\ub\src\install\UsenetBackup.wxs", [Convert]::FromBase64String($wxsB64))
[IO.File]::WriteAllBytes("C:\ub\src\winpe\build-winpe.ps1", [Convert]::FromBase64String($winpeB64))
Write-Host ("  UsenetBackup.wxs: {0:N0} bytes" -f (Get-Item C:\ub\src\install\UsenetBackup.wxs).Length)
Write-Host ("  build-winpe.ps1:  {0:N0} bytes" -f (Get-Item C:\ub\src\winpe\build-winpe.ps1).Length)

Write-Host "=== 2/5 Re-publishing apps as single-file ==="
cd C:\ub\src
dotnet publish src/UsenetBackup.Cli/UsenetBackup.Cli.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\cli /p:PublishSingleFile=true
if ($LASTEXITCODE -ne 0) { throw "CLI publish failed" }
dotnet publish src/UsenetBackup.Service/UsenetBackup.Service.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\service /p:PublishSingleFile=true
if ($LASTEXITCODE -ne 0) { throw "Service publish failed" }
dotnet publish src/UsenetBackup.Recovery/UsenetBackup.Recovery.csproj -c Release -r win-x64 --self-contained -o C:\ub\publish\recovery /p:PublishSingleFile=true
if ($LASTEXITCODE -ne 0) { throw "Recovery publish failed" }

Write-Host "=== 3/5 Verifying required MSI payload files ==="
$required = @(
    "C:\ub\publish\cli\usenet-backup.exe",
    "C:\ub\publish\service\usenet-backup-service.exe",
    "C:\ub\publish\recovery\usenet-backup-recovery.exe"
)
foreach ($f in $required) {
    if (Test-Path $f) { Write-Host ("  OK: {0} ({1:N0} bytes)" -f $f, (Get-Item $f).Length) }
    else { throw "MISSING required MSI payload: $f" }
}

Write-Host "=== 4/5 Building MSI ==="
wix build -arch x64 -d CliBin=C:\ub\publish\cli -d ServiceBin=C:\ub\publish\service -d RecoveryBin=C:\ub\publish\recovery -o C:\ub\usenet-backup-0.8.0-x64.msi install/UsenetBackup.wxs
if ($LASTEXITCODE -ne 0) { throw "wix build failed" }
$msi = Get-Item C:\ub\usenet-backup-0.8.0-x64.msi
Write-Host ("  MSI built: {0:N0} bytes" -f $msi.Length)

Write-Host "=== 5/5 Test install + verify + uninstall ==="
Start-Process msiexec -ArgumentList "/i", "C:\ub\usenet-backup-0.8.0-x64.msi", "/qn" -Wait
Start-Sleep 15
foreach ($c in @("C:\Program Files\UsenetBackup\cli\usenet-backup.exe",
                 "C:\Program Files\UsenetBackup\service\usenet-backup-service.exe",
                 "C:\Program Files\UsenetBackup\wizard\usenet-backup-recovery.exe")) {
    if (Test-Path $c) { Write-Host "  OK installed: $c" } else { throw "MISSING after install: $c" }
}
$svc = sc.exe query UsenetBackup
Write-Host "  Service state:"
Write-Host $svc
if ($svc -notmatch "RUNNING") { Write-Host "  WARNING: service not running after install" }

Write-Host "  Uninstalling..."
Start-Process msiexec -ArgumentList "/x", "C:\ub\usenet-backup-0.8.0-x64.msi", "/qn" -Wait
Start-Sleep 10
if (Test-Path "C:\Program Files\UsenetBackup") { throw "Uninstall left files behind" }
Write-Host "  Uninstall clean."

Write-Host ""
Write-Host "ALL DONE - MSI built, installed, verified, and uninstalled cleanly."
