using UsenetBackup.Core.Redundancy;
using Xunit;

namespace UsenetBackup.Core.Tests;

/// <summary>
/// Tests for <see cref="LegacyReedSolomon"/> (RS1 magic), the handmade
/// Vandermonde codec used 2026-10-05 to 2026-10-08. Retained ONLY for
/// decoding old RS1 parity blocks; new parity is RS2 (ReedSolomonFast).
///
/// Uses archived writer vectors: fixed data/parity bytes generated by the
/// RS1 encoder, so the decoder is validated against the frozen on-disk
/// format rather than against itself. Multiple missing-shard patterns are
/// covered, including the combinations most likely in real recovery.
/// </summary>
public sealed class LegacyReedSolomonTests
{
    // Archived RS1 test vectors — generated 2026-10-09 by a faithful port
    // of GaloisField.cs (poly 0x11D) + LegacyReedSolomon.Encode.
    // Config: 4 data shards, 2 parity shards, 16 bytes/shard.
    private static readonly byte[] Rs1Data0 = new byte[] { 0xF7, 0x5D, 0x3E, 0x49, 0xF4, 0x41, 0xAF, 0x1C, 0x58, 0x6C, 0x7A, 0x22, 0xB3, 0xEF, 0x32, 0x58 };
    private static readonly byte[] Rs1Data1 = new byte[] { 0x38, 0xB8, 0xF0, 0x60, 0x06, 0x2D, 0xA4, 0x1B, 0x5D, 0x91, 0xD2, 0x15, 0x2C, 0x5E, 0xC2, 0x45 };
    private static readonly byte[] Rs1Data2 = new byte[] { 0x96, 0x24, 0xD9, 0x36, 0x6E, 0xC1, 0x49, 0x90, 0x55, 0x37, 0x1B, 0xCD, 0x5D, 0xB2, 0xD6, 0x64 };
    private static readonly byte[] Rs1Data3 = new byte[] { 0x54, 0x20, 0x5B, 0xA2, 0x89, 0x84, 0xD8, 0x81, 0x69, 0x08, 0xA5, 0xA3, 0x78, 0xE4, 0x2F, 0x50 };
    private static readonly byte[] Rs1Parity0 = new byte[] { 0x0D, 0xE1, 0x4C, 0xBD, 0x15, 0x29, 0x9A, 0x16, 0x39, 0xC2, 0x16, 0x59, 0xBA, 0xE7, 0x09, 0x29 };
    private static readonly byte[] Rs1Parity1 = new byte[] { 0x7F, 0xBD, 0x62, 0x28, 0x61, 0x6C, 0x4D, 0x2C, 0xC4, 0xCF, 0xEE, 0x6A, 0x65, 0xD2, 0xB1, 0xE5 };

    private static readonly byte[][] AllData = new[] { Rs1Data0, Rs1Data1, Rs1Data2, Rs1Data3 };
    private static readonly byte[][] AllParity = new[] { Rs1Parity0, Rs1Parity1 };

    /// <summary>
    /// Builds the full 6-shard array (4 data + 2 parity) with the given
    /// data-shard indices marked missing (null) and the present flags set.
    /// </summary>
    private static (byte[][] shards, bool[] present) BuildShards(
        int[] missingDataIndices, int[] missingParityIndices)
    {
        var shards = new byte[6][];
        var present = new bool[6];
        for (int i = 0; i < 4; i++)
        {
            if (System.Array.IndexOf(missingDataIndices, i) >= 0)
            {
                shards[i] = null!;
                present[i] = false;
            }
            else
            {
                shards[i] = (byte[])AllData[i].Clone();
                present[i] = true;
            }
        }
        for (int p = 0; p < 2; p++)
        {
            if (System.Array.IndexOf(missingParityIndices, p) >= 0)
            {
                shards[4 + p] = null!;
                present[4 + p] = false;
            }
            else
            {
                shards[4 + p] = (byte[])AllParity[p].Clone();
                present[4 + p] = true;
            }
        }
        return (shards, present);
    }

    private static void AssertDataRecovered(byte[][] reconstructed)
    {
        Assert.Equal(4, reconstructed.Length);
        for (int i = 0; i < 4; i++)
            Assert.Equal(AllData[i], reconstructed[i]);
    }

    [Fact]
    public void Rs1_Decode_AllShardsPresent_Passthrough()
    {
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([], []);
        AssertDataRecovered(rs.Reconstruct(shards, present));
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    public void Rs1_Decode_SingleMissingDataShard(int missing)
    {
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([missing], []);
        AssertDataRecovered(rs.Reconstruct(shards, present));
    }

    [Theory]
    [InlineData(0, 1)]
    [InlineData(0, 2)]
    [InlineData(0, 3)]
    [InlineData(1, 2)]
    [InlineData(1, 3)]
    [InlineData(2, 3)]
    public void Rs1_Decode_TwoMissingDataShards(int m1, int m2)
    {
        // Maximum erasure capacity for 2 parity shards.
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([m1, m2], []);
        AssertDataRecovered(rs.Reconstruct(shards, present));
    }

    [Fact]
    public void Rs1_Decode_MissingParityShards_DataIntact()
    {
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([], [0, 1]);
        AssertDataRecovered(rs.Reconstruct(shards, present));
    }

    [Theory]
    [InlineData(0, 0)]
    [InlineData(3, 1)]
    [InlineData(1, 0)]
    public void Rs1_Decode_MissingDataAndParity(int missingData, int missingParity)
    {
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([missingData], [missingParity]);
        AssertDataRecovered(rs.Reconstruct(shards, present));
    }

    [Fact]
    public void Rs1_Decode_ThreeMissingDataShards_Throws()
    {
        // Beyond erasure capacity (2 parity): must fail, not silently
        // produce garbage.
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([0, 1, 2], []);
        Assert.Throws<InvalidOperationException>(() => rs.Reconstruct(shards, present));
    }

    [Fact]
    public void Rs1_Decode_CorruptedDataShard_DetectableByHash()
    {
        // Flip a byte in a PRESENT data shard: the RS math will happily
        // "reconstruct" around it, producing wrong output for the missing
        // shard. This is why the Par2 layer SHA256-checks reconstructed
        // bytes against chunk IDs — the codec alone cannot detect this.
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([3], []);
        shards[0][0] ^= 0xFF; // corrupt a present shard

        byte[][] reconstructed = rs.Reconstruct(shards, present);

        // The corrupted input must NOT yield the original data — proving
        // that hash validation (done by the caller) is load-bearing.
        Assert.NotEqual(AllData[3], reconstructed[3]);
    }

    [Fact]
    public void Rs1_Decode_CorruptedParityShard_WrongReconstruction()
    {
        // Corrupted parity poisons reconstruction of a missing data shard.
        var rs = new LegacyReedSolomon(4, 2);
        var (shards, present) = BuildShards([2], []);
        shards[4][5] ^= 0xFF; // corrupt parity[0]

        byte[][] reconstructed = rs.Reconstruct(shards, present);
        Assert.NotEqual(AllData[2], reconstructed[2]);
    }

    [Fact]
    public void Rs1_Encode_MatchesArchivedParity()
    {
        // The encoder must reproduce the archived vectors byte-for-byte.
        // If this fails, the vectors (not the code) are the reference.
        var rs = new LegacyReedSolomon(4, 2);
        byte[][] parity = rs.Encode(AllData.Select(d => (byte[])d.Clone()).ToArray());
        Assert.Equal(2, parity.Length);
        Assert.Equal(AllParity[0], parity[0]);
        Assert.Equal(AllParity[1], parity[1]);
    }

    [Fact]
    public void Rs1_RoundTrip_RandomData()
    {
        // Encode/decode round-trip with random data and random erasures.
        var rng = new Random(12345);
        var rs = new LegacyReedSolomon(4, 2);
        byte[][] data = new byte[4][];
        for (int i = 0; i < 4; i++)
        {
            data[i] = new byte[32];
            rng.NextBytes(data[i]);
        }
        byte[][] parity = rs.Encode(data);

        // Lose 2 random data shards
        int[] missing = new[] { rng.Next(4), rng.Next(4) }.Distinct().ToArray();
        while (missing.Length < 2)
            missing = new[] { rng.Next(4), rng.Next(4) }.Distinct().ToArray();

        var shards = new byte[6][];
        var present = new bool[6];
        for (int i = 0; i < 4; i++)
        {
            if (System.Array.IndexOf(missing, i) >= 0) { shards[i] = null!; present[i] = false; }
            else { shards[i] = data[i]; present[i] = true; }
        }
        shards[4] = parity[0]; present[4] = true;
        shards[5] = parity[1]; present[5] = true;

        byte[][] recovered = rs.Reconstruct(shards, present);
        for (int i = 0; i < 4; i++)
            Assert.Equal(data[i], recovered[i]);
    }
}
